import { useState } from "react";
import type { CourseOperationsPatch, LiveStatus } from "../hooks/useLiveSimulation";
import { unlockedStaffRoles } from "../game/progression/progression";
import { translateCurrent } from "../i18n/core";
import type { CourseOperations, PacePreset, StaffMember } from "../game/models/types";

type Tab = "golfers" | "leaderboard" | "staff" | "pace";
const TAB_LABELS = { golfers: "live.tab.golfers", leaderboard: "live.tab.leaderboard", staff: "live.tab.staff", pace: "live.tab.pace" } as const;

function score(value: number) { return value === 0 ? "E" : value > 0 ? `+${value}` : `${value}`; }

export function LiveOverview(props: { status: LiveStatus; reputation: number; staffLevel: number; staffRoster?: StaffMember[]; courses?: Array<{ id: string; name: string }>; onAssignStaff?: (staffId: string, courseId: string) => void; onSelectGolfer: (id: number) => void; onSetPacePreset?: (preset: PacePreset) => void; onUpdatePaceOperations?: (patch: CourseOperationsPatch) => void; onClose: () => void }) {
  const [tab, setTab] = useState<Tab>("golfers");
  const golfers = [...props.status.golfers];
  const leaderboard = props.status.tournament
    ? props.status.tournament.standings.map((row) => ({ id: row.entrantId, name: row.name, scoreToPar: row.scoreToPar, thru: row.holesCompleted }))
    : [...golfers].sort((a, b) => a.scoreToPar - b.scoreToPar || b.currentHole - a.currentHole).map((row) => ({ id: String(row.id), name: row.name, scoreToPar: row.scoreToPar, thru: Math.max(0, row.currentHole) }));
  const roles = unlockedStaffRoles(props.reputation);
  return <aside className="cc-live-overview" data-testid="live-overview" style={{ position: "absolute", right: 14, top: 14, zIndex: 125, width: "min(360px,calc(100% - 28px))", maxHeight: "calc(100% - 110px)", overflow: "auto", padding: 13, borderRadius: 12, background: "rgba(24,33,26,.94)", color: "#f6f4e8", boxShadow: "0 10px 30px rgba(0,0,0,.4)" }}>
    <header style={{ display: "flex", gap: 8, alignItems: "center" }}><div style={{ flex: 1 }}><strong style={{ fontSize: 16 }}>{translateCurrent("live.overview")}</strong><div style={{ fontSize: 11, opacity: .7 }}>{translateCurrent("live.arrivals", { count: props.status.arrivalsRemaining })}</div></div><button aria-label={translateCurrent("live.closeOverview")} onClick={props.onClose}>✕</button></header>
    <div role="tablist" aria-label={translateCurrent("live.overviewTabs")} style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 4, margin: "11px 0" }}>
      {(["golfers", "leaderboard", "staff", "pace"] as Tab[]).map((name) => <button role="tab" aria-selected={tab === name} key={name} onClick={() => setTab(name)} style={{ padding: 7, borderRadius: 7, border: tab === name ? "1px solid #9bd18a" : "1px solid rgba(255,255,255,.18)", background: tab === name ? "rgba(112,171,91,.28)" : "rgba(255,255,255,.06)", color: "inherit" }}>{translateCurrent(TAB_LABELS[name])}</button>)}
    </div>
    {tab === "golfers" && <div style={{ display: "grid", gap: 5 }}>{golfers.length === 0 ? <small>{translateCurrent("live.noGolfers")}</small> : golfers.slice(0, 24).map((golfer) => <button key={golfer.id} onClick={() => props.onSelectGolfer(golfer.id)} style={{ display: "grid", gridTemplateColumns: "1fr auto auto", gap: 8, textAlign: "left", alignItems: "center", padding: 8, borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(255,255,255,.06)", color: "inherit" }}><span><b>{golfer.name}</b><br /><small style={{ opacity: .65 }}>{golfer.currentHole >= 0 ? translateCurrent("live.hole", { hole: golfer.currentHole + 1 }) : translateCurrent("live.clubhouse")}</small></span><span>{score(golfer.scoreToPar)}</span><span title={translateCurrent("live.mood")}>{golfer.mood >= .65 ? "☺" : golfer.mood < .35 ? "☹" : "•"}</span></button>)}</div>}
    {tab === "leaderboard" && <ol style={{ margin: 0, paddingLeft: 24 }}>{leaderboard.slice(0, 12).map((row) => <li key={row.id} style={{ padding: "5px 0" }}><span style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><b>{row.name}</b><span>{score(row.scoreToPar)} · {row.thru} {translateCurrent("golfer.thru")}</span></span></li>)}</ol>}
    {tab === "staff" && <div><div style={{ padding: 9, borderRadius: 8, background: "rgba(255,255,255,.07)" }}><strong>{translateCurrent("live.staffCoverage", { active: props.staffRoster?.length ?? props.staffLevel, available: roles.length })}</strong><div style={{ fontSize: 12, opacity: .72 }}>{translateCurrent("live.staffHint")}</div></div>{props.staffRoster?.length ? <div style={{ display: "grid", gap: 6, marginTop: 8 }}>{props.staffRoster.map((member) => <label key={member.id} style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: 8, padding: 7, borderRadius: 7, background: "rgba(255,255,255,.06)" }}><span><b>{member.name}</b><br/><small style={{ textTransform: "capitalize", opacity: .7 }}>{member.role.replaceAll("_", " ")} · {translateCurrent("live.weeklyWage", { wage: member.weeklyWage })}</small></span><select aria-label={translateCurrent("live.assignStaff", { name: member.name })} value={member.courseId ?? ""} onChange={(event) => props.onAssignStaff?.(member.id, event.target.value)} style={{ maxWidth: 120 }}>{props.courses?.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label>)}</div> : <ul style={{ marginBottom: 0 }}>{roles.map((role, index) => <li key={role} style={{ opacity: index < props.staffLevel ? 1 : .55, padding: "3px 0" }}>{index < props.staffLevel ? "●" : "○"} {role} — {index < props.staffLevel ? translateCurrent("live.onDuty") : translateCurrent("live.available")}</li>)}</ul>}</div>}
    {tab === "pace" && <div data-testid="pace-operations" style={{ display: "grid", gap: 9 }}>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 5 }}>{(["relaxed", "balanced", "brisk"] as PacePreset[]).map((preset) => <button key={preset} aria-pressed={props.status.pace.preset === preset} onClick={() => props.onSetPacePreset?.(preset)} style={{ textTransform: "capitalize", padding: 8, borderRadius: 7, color: "inherit", border: props.status.pace.preset === preset ? "1px solid #9bd18a" : "1px solid rgba(255,255,255,.18)", background: props.status.pace.preset === preset ? "rgba(112,171,91,.28)" : "rgba(255,255,255,.06)" }}>{preset}</button>)}</div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 7 }}><label style={{ display: "grid", gap: 3, fontSize: 11 }}>{translateCurrent("live.pace.teeInterval")}<input aria-label={translateCurrent("live.pace.teeIntervalAria")} type="number" min={7} max={15} value={props.status.pace.teeIntervalMinutes} onChange={(event) => props.onUpdatePaceOperations?.({ teeIntervalMinutes: Number(event.target.value) })}/></label><label style={{ display: "grid", gap: 3, fontSize: 11 }}>{translateCurrent("live.pace.beverageService")}<select aria-label={translateCurrent("live.pace.beverageService")} value={props.status.pace.beverageMenu} onChange={(event) => props.onUpdatePaceOperations?.({ beverage: { menu: event.target.value as CourseOperations["beverage"]["menu"] } })}><option value="off">{translateCurrent("common.off")}</option><option value="refreshments">{translateCurrent("live.pace.refreshments")}</option><option value="beer_wine">{translateCurrent("live.pace.beerWine")}</option></select></label></div>
      <div style={{ padding: 9, borderRadius: 8, background: "rgba(255,255,255,.07)", display: "grid", gridTemplateColumns: "1fr auto", gap: 5, fontSize: 12 }}>
        <span>{translateCurrent("live.pace.teeInterval")}</span><b>{translateCurrent("live.pace.minutes", { minutes: props.status.pace.teeIntervalMinutes })}</b><span>{translateCurrent("live.pace.maximumGroup")}</span><b>{props.status.pace.maxGroupSize}</b><span>{translateCurrent("live.pace.groupsBlocked")}</span><b>{props.status.pace.groupsOnCourse} / {props.status.pace.blockedGroups}</b><span>{translateCurrent("live.pace.averageWait")}</span><b>{translateCurrent("live.pace.minutes", { minutes: props.status.pace.averageWaitMinutes.toFixed(1) })}</b><span>{translateCurrent("live.pace.marshalCoverage")}</span><b>{props.status.pace.marshalCoverage}</b><span>{translateCurrent("live.pace.interventionsPickups")}</span><b>{props.status.pace.interventions} / {props.status.pace.pickups}</b><span>{translateCurrent("live.pace.beverageCoverage")}</span><b>{props.status.pace.beverageCoverage}</b><span>{translateCurrent("live.pace.beverageRevenue")}</span><b>${props.status.pace.beverageRevenue}</b><span>{translateCurrent("live.pace.alcoholIncidents")}</span><b>{props.status.pace.alcoholicDrinks} / {props.status.pace.incidents}</b>
      </div>
      <small style={{ opacity: .72 }}>{translateCurrent("live.pace.policyHint")}</small>
    </div>}
  </aside>;
}
