import assert from "node:assert/strict";
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync, symlinkSync, realpathSync, lstatSync, renameSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { resolve, dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { verifyZk682WorkflowReport } from "./zk682-workflow-verdict.mjs";

const COMMIT = "a".repeat(40);
const workflowPath = fileURLToPath(new URL("../../.github/workflows/zk682-certification.yml", import.meta.url));
const currentCaptureWorkflow = readFileSync(workflowPath, "utf8");
function inverseCurrentCaptureWorkflow(source) { const marker="\n  current-capture-phase-eebb:\n",choice="          - current-capture-phase-eebb\n";assert.equal(source.split(marker).length-1,1);assert.equal(source.split(choice).length-1,1);return source.slice(0,source.indexOf(marker)).replace(choice,""); }
const workflow = inverseCurrentCaptureWorkflow(currentCaptureWorkflow);
const jobsText = workflow.split("\njobs:\n")[1];

function jobBlock(jobId, nextJobId) {
  const start = jobsText.indexOf(`  ${jobId}:\n`);
  assert.notEqual(start, -1, `missing ${jobId} job`);
  const end = nextJobId ? jobsText.indexOf(`  ${nextJobId}:\n`, start + 1) : jobsText.length;
  assert.notEqual(end, -1, `missing ${nextJobId} job boundary`);
  return jobsText.slice(start, end);
}

test("workflow is manual-only and requires one full candidate input", () => {
  const triggers = workflow.slice(0, workflow.indexOf("\npermissions:"));
  assert.match(triggers, /workflow_dispatch:\n    inputs:\n      candidate_sha:/);
  assert.match(triggers, /candidate_sha:[\s\S]*?required: true[\s\S]*?type: string/);
  assert.doesNotMatch(triggers, /^  (?:push|pull_request|schedule):/m);
  assert.doesNotMatch(workflow.split("\n  renderer-recording-ablation:\n")[0], /github\.sha|GITHUB_SHA/);
});

test("every job checks out, verifies, and binds the requested full SHA", () => {
  const jobs = [["linux-evidence", "native-evidence"], ["native-evidence", "aggregate"], ["aggregate", null]];
  for (const [jobId, nextJobId] of jobs) {
    const block = jobBlock(jobId, nextJobId);
    assert.match(block, /ZK682_EXPECTED_COMMIT: \$\{\{ inputs\.candidate_sha \}\}/);
    assert.match(block, /uses: actions\/checkout@v4[\s\S]*?ref: \$\{\{ inputs\.candidate_sha \}\}/);
    assert.match(block, /Verify exact candidate checkout[\s\S]*?\^\[0-9a-f\]\{40\}\$[\s\S]*?git rev-parse HEAD/);
  }
});

test("Windows disables checkout newline conversion before the native checkout", () => {
  const native = jobBlock("native-evidence", "aggregate");
  const normalization = native.indexOf("- name: Disable Windows checkout newline conversion");
  const checkout = native.indexOf("- name: Checkout exact candidate");
  assert.notEqual(normalization, -1);
  assert.notEqual(checkout, -1);
  assert(normalization < checkout, "Windows newline normalization must run before checkout");
  assert.match(native.slice(normalization, checkout), /if: runner\.os == 'Windows'[\s\S]*?working-directory: \$\{\{ github\.workspace \}\}[\s\S]*?git config --global core\.autocrlf false/);
});

test("same-run aggregation names and retention are exact", () => {
  const linux = jobBlock("linux-evidence", "native-evidence");
  const native = jobBlock("native-evidence", "aggregate");
  const aggregate = jobBlock("aggregate", null);
  assert.match(linux, /name: zk682-linux-evidence-\$\{\{ inputs\.candidate_sha \}\}[\s\S]*?retention-days: 90/);
  assert.match(native, /name: zk682-native-evidence-\$\{\{ matrix\.platform \}\}-\$\{\{ matrix\.architecture \}\}-\$\{\{ inputs\.candidate_sha \}\}[\s\S]*?retention-days: 90/);
  assert.match(native, /name: coursecraft-\$\{\{ matrix\.platform \}\}-\$\{\{ matrix\.architecture \}\}-unsigned-\$\{\{ inputs\.candidate_sha \}\}[\s\S]*?retention-days: 30/);
  for (const name of [
    "zk682-linux-evidence-${{ inputs.candidate_sha }}",
    "zk682-native-evidence-darwin-arm64-${{ inputs.candidate_sha }}",
    "zk682-native-evidence-win32-x64-${{ inputs.candidate_sha }}",
  ]) assert.ok(aggregate.includes(`name: ${name}`));
  assert.match(aggregate, /npm run release:build:zk682/);
  assert.match(aggregate, /name: zk682-certification-packet-\$\{\{ inputs\.candidate_sha \}\}[\s\S]*?retention-days: 90/);
  assert.match(aggregate, /if: always\(\)[\s\S]*?Require passing machine gates and physical-only blockers/);
});

test("workflow verdict accepts GO or a physical-only HOLD", () => {
  const hold = verifyZk682WorkflowReport({ candidateCommit: COMMIT, machinePassed: true, decision: "HOLD", blockers: [
    { criterionId: "midrange-physical-p95" },
    { criterionId: "low-end-physical-p95" },
  ] }, COMMIT);
  assert.deepEqual(hold, { valid: true, errors: [] });
  assert.equal(verifyZk682WorkflowReport({ candidateCommit: COMMIT, machinePassed: true, decision: "GO", blockers: [] }, COMMIT).valid, true);
});

test("workflow verdict rejects candidate drift, machine failures, and non-physical blockers", () => {
  assert.equal(verifyZk682WorkflowReport({ candidateCommit: "b".repeat(40), machinePassed: true, decision: "GO", blockers: [] }, COMMIT).valid, false);
  assert.equal(verifyZk682WorkflowReport({ candidateCommit: COMMIT, machinePassed: false, decision: "HOLD", blockers: [{ criterionId: "core-build" }] }, COMMIT).valid, false);
  assert.equal(verifyZk682WorkflowReport({ candidateCommit: COMMIT, machinePassed: true, decision: "HOLD", blockers: [{ criterionId: "core-build" }] }, COMMIT).valid, false);
});


test("diagnostic modes cannot launch certification batch and preserve missing-mode default", () => {
  for (const id of ["linux-evidence", "native-evidence", "aggregate"]) {
    const start=jobsText.indexOf(`  ${id}:\n`);
    assert.match(jobsText.slice(start,start+150), /!inputs\.mode \|\| inputs\.mode == 'certification'/);
  }
  for (const id of ["renderer", "startup"]) {
    const start=jobsText.indexOf(`  ${id}-diagnostic:\n`);
    assert.notEqual(start,-1);
    const next=jobsText.slice(start+4).search(/\n  [a-z][a-z-]*:\n/);
    const end=next<0?-1:start+4+next;
    const block=jobsText.slice(start,end<0?undefined:end);
    assert.match(block,new RegExp(`inputs\\.mode == '${id}-diagnostic'`));
  }
  assert.match(workflow,/git -C \.\. diff --exit-code ab8f4e2/);
  assert.match(workflow,/default: certification/);
  assert.match(workflow,/--seconds 1850 --parent-seconds 1910/);
  assert.match(workflow,/--seconds 600 --parent-seconds 660/);
  assert.doesNotMatch(workflow,/artifacts\/linux-[^\n]*\/\*\.(?:png|zip|webm)/);
});

function embeddedAblation(marker,flag){const block=workflow.split(`# BEGIN RECORDING ${marker}\n`)[1].split(`# END RECORDING ${marker}`)[0];const code=block.split("node --input-type=module <<'NODE'\n")[1].split('\n          NODE')[0].split('\n').map(line=>line.slice(10)).join('\n');process.env[flag]='1';return import('data:text/javascript,'+encodeURIComponent(code));}
test("recording ablation transform has exact inverse and app-root location",async()=>{
 const c=await embeddedAblation('CONTROLLER','ZK682_RECORDING_CONTROLLER_TEST');const path=fileURLToPath(new URL('../playwright.zk682-linux-diagnostic.config.ts',import.meta.url));const before=readFileSync(path,'utf8'),after=c.transformConfig(before);let inverse=after;for(const [from,to]of [...c.edits].reverse())inverse=inverse.replace(to,from);assert.equal(inverse,before);
 for(const [literal]of c.edits){assert.throws(()=>c.transformConfig(before.replace(literal,'')));assert.throws(()=>c.transformConfig(before+literal));}
 assert.throws(()=>c.transformConfig(before.replace('trace: "retain-on-failure"','trace: "on"')));
 assert.match(after,/testDir: "\.\/diagnostics"/);assert.match(after,/testMatch: "zk682-linux-renderer\.diagnostic\.ts"/);assert.match(after,/timeout: 600_000/);assert.match(after,/workers: 1/);assert.match(after,/retries: 0/);
 assert.equal(resolve(dirname(path),'./diagnostics'),fileURLToPath(new URL('../diagnostics',import.meta.url)));
 const code=workflow.split('# BEGIN RECORDING CONTROLLER')[1].split('# END RECORDING CONTROLLER')[0];assert.match(code,/flag:'wx'/);assert.match(code,/resolve\(cwd,'playwright\.zk682-recording-off\.generated\.config\.ts'\)/);assert.doesNotMatch(code,/Object\.entries\(aliases\)\.map/);assert.match(code,/Object\.entries\(\{DIAG_APP_BASELINE:/);
});
test("recording ablation routing evaluates exclusively and old workflow prefix is exact",()=>{
 const ids=['linux-evidence','native-evidence','aggregate','renderer-diagnostic','startup-diagnostic','renderer-recording-ablation'];
 const active=mode=>ids.filter(id=>{const body=jobsText.slice(jobsText.indexOf(`  ${id}:\n`));const expression=body.match(/if: \$\{\{ (.*?) \}\}/)[1];return Function('inputs',`return (${expression});`)({mode});});
 assert.deepEqual(active(undefined),['linux-evidence','native-evidence','aggregate']);assert.deepEqual(active('certification'),['linux-evidence','native-evidence','aggregate']);assert.deepEqual(active('renderer-recording-ablation'),['renderer-recording-ablation']);assert.deepEqual(active('renderer-diagnostic'),['renderer-diagnostic']);assert.deepEqual(active('startup-diagnostic'),['startup-diagnostic']);
 const prior=workflow.split('\n  renderer-recording-ablation:\n')[0].replace('          - renderer-recording-ablation\n','').replace('          - canonical-renderer-verification\n','');assert.equal(createHash('sha256').update(prior).digest('hex'),'2aa9cdb774c254bc9ed68dc13a8eb294eec8df9e34831d34bbe7566bf258fe43');
 const block=jobBlock('renderer-recording-ablation',null);assert.match(block,/fetch-depth: 3/);assert.match(block,/--seconds 1850 --parent-seconds 1910/);assert.match(block,/env GITHUB_SHA="\$DIAG_APP_BASELINE" VITE_COMMIT_SHA="\$DIAG_APP_BASELINE" ZK682_EXPECTED_COMMIT="\$DIAG_APP_BASELINE" python3/);assert.match(block,/steps\.recording_artifact_bounds\.conclusion == 'success'/);
});
test("recording ablation real Git fixture catches changed App from simcwd and aliases actual child",async()=>{
 const c=await embeddedAblation('CONTROLLER','ZK682_RECORDING_CONTROLLER_TEST');const repo=mkdtempSync(join(tmpdir(),'zk682-ablation-git-'));const cwd=join(repo,'simgolf-lite');const git=(...args)=>execFileSync('git',args,{cwd:repo,encoding:'utf8',timeout:10000,maxBuffer:65536}).trim();
 try {mkdirSync(join(cwd,'src'),{recursive:true});writeFileSync(join(cwd,'src/app.ts'),'base\n');git('init');git('config','user.email','fixture@example.invalid');git('config','user.name','Fixture');git('add','.');git('commit','-m','App baseline');const app=git('rev-parse','HEAD');writeFileSync(join(repo,'diagnostic'),'donor');git('add','.');git('commit','-m','d7 fixture');const parent=git('rev-parse','HEAD');writeFileSync(join(repo,'ablation'),'driver');git('add','.');git('commit','-m','new driver');const driver=git('rev-parse','HEAD');const identity=c.verifyApp(cwd,driver,app,parent);const aliases=c.childAliases(identity);const child=JSON.parse(execFileSync(process.execPath,['-e','console.log(JSON.stringify({driver:process.env.DIAG_DRIVER_SHA,app:process.env.ZK682_EXPECTED_COMMIT,github:process.env.GITHUB_SHA,vite:process.env.VITE_COMMIT_SHA}))'],{env:{...process.env,...aliases},encoding:'utf8',timeout:10000,maxBuffer:65536}));assert.deepEqual(child,{driver,app,github:app,vite:app});
 assert.throws(()=>c.verifyApp(cwd,driver,'f'.repeat(40),parent));assert.throws(()=>c.verifyApp(cwd,'0'.repeat(40),app,parent));assert.throws(()=>c.verifyApp(cwd,driver,app,'0'.repeat(40)));
 writeFileSync(join(cwd,'src/app.ts'),'changed\n');git('add','.');git('commit','--amend','--no-edit');assert.throws(()=>c.verifyApp(cwd,git('rev-parse','HEAD'),app,parent));
 }finally{rmSync(repo,{recursive:true,force:true});}
});
test("recording ablation artifact helper rejects unknown/prototype/symlink/oversize inputs",async()=>{
 const c=await embeddedAblation('BOUNDS','ZK682_RECORDING_BOUNDS_TEST');const root=mkdtempSync(join(tmpdir(),'zk682-ablation-art-'));try{
 for(const name of ['unknown.json','__proto__','constructor','toString'])assert.throws(()=>c.boundedArtifact(root,name));assert.equal(c.boundedArtifact(root,'phase.json'),0);writeFileSync(join(root,'phase.json'),'{}');assert.equal(c.boundedArtifact(root,'phase.json'),2);
 writeFileSync(join(root,'phase.json'),Buffer.alloc(65537));assert.throws(()=>c.boundedArtifact(root,'phase.json'));rmSync(join(root,'phase.json'));symlinkSync('/tmp',join(root,'stdout.log'));assert.throws(()=>c.boundedArtifact(root,'stdout.log'));rmSync(join(root,'stdout.log'));assert.equal(c.validateBounds(root,[]),0);
 }finally{rmSync(root,{recursive:true,force:true});}
});

function embeddedCanonical(marker,flag){const block=workflow.split(`# BEGIN CANONICAL ${marker}\n`)[1].split(`# END CANONICAL ${marker}`)[0];const code=block.split("node --input-type=module <<'NODE'\n")[1].split('\n          NODE')[0].split('\n').map(line=>line.slice(10)).join('\n');process.env[flag]='1';return import('data:text/javascript,'+encodeURIComponent(code));}
const canonicalBlock=jobBlock('canonical-renderer-verification',null);
test('canonical mode exclusively routes and removes to byte-exact af0 workflow',()=>{
 const ids=['linux-evidence','native-evidence','aggregate','renderer-diagnostic','startup-diagnostic','renderer-recording-ablation','canonical-renderer-verification'];
 const active=mode=>ids.filter(id=>Function('inputs',`return (${jobBlock(id,null).match(/if: \$\{\{ (.*?) \}\}/)[1]});`)({mode}));
 assert.deepEqual(active(undefined),['linux-evidence','native-evidence','aggregate']);assert.deepEqual(active('certification'),['linux-evidence','native-evidence','aggregate']);for(const mode of ids.slice(3))assert.deepEqual(active(mode),[mode]);assert.deepEqual(active('unknown'),[]);
 const inverse=workflow.slice(0,workflow.indexOf('\n  canonical-renderer-verification:\n')).replace('          - canonical-renderer-verification\n','');assert.equal(createHash('sha256').update(inverse).digest('hex'),'10c76ebbd93ce73b19c4492a99c4852509b98094b18bc71e2a77329fba44b96e');
 for(const [id,pin]of Object.entries({"linux-evidence":"59f7db79571e57fe62acc8f668d2ff50a2b749b6ba4e1fc3f84a05bdfdc2eed2","native-evidence":"8be9df6e5109641a3924517652d24aa83c92df6ef55b916740c0df817c0c5ca6","aggregate":"8687a84e4c357ec170ce7c8cfba9ead432146ef24f1341fad2c408c3f601b7fd","renderer-diagnostic":"7cad87dc22e2a2cb798d5dea4d96fdb4d03df338a628cb100351e05d17218d4e","startup-diagnostic":"0e87b8112911b0698402db67dd2abd7e4d57317e2753bf4735e1fa7ef7bec0d7","renderer-recording-ablation":"29f1bab5a4a38fd4dcaa37dcbbc3dab5a0c59c9f98f44c2b17bf639627fec3c5"})){const text=inverse.split('\njobs:\n')[1],start=text.indexOf(`  ${id}:\n`),tail=text.slice(start),next=tail.slice(4).search(/\n  [a-z][a-z-]*:\n/);assert.equal(createHash('sha256').update(next<0?tail:tail.slice(0,4+next+1)).digest('hex'),pin,'old job inverse '+id);}
 assert.doesNotMatch(canonicalBlock,/continue-on-error|needs:|deploy|release:build|generated\.config|phase\.json|diagnostic\.ts/);
});
test('canonical actual command scope preserves one original wrapper and finite budgets',async()=>{
 const c=await embeddedCanonical('CONTROLLER','ZK682_CANONICAL_CONTROLLER_TEST');const identity={targetCommit:c.targetCandidate,driverCommit:'d'.repeat(40),driverRoot:'/driver'};
 assert.deepEqual(c.canonicalCommand(identity),['env','GITHUB_SHA='+c.targetCandidate,'VITE_COMMIT_SHA='+c.targetCandidate,'ZK682_EXPECTED_COMMIT='+c.targetCandidate,'python3','/driver/simgolf-lite/scripts/linux-diagnostic-supervisor.py','--out','artifacts/canonical-renderer-verification/run','--seconds','1850','--parent-seconds','1910','--artifact-cap','1048576','--','node','scripts/zk682-run-resource-growth.mjs','--expected-commit',c.targetCandidate]);
 assert.match(canonicalBlock,/timeout-minutes: 40/);assert.match(canonicalBlock,/ref: \$\{\{ github\.sha \}\}/);assert.match(canonicalBlock,/path: target/);assert.match(canonicalBlock,/cache-dependency-path: target\/simgolf-lite\/package-lock\.json/);
 const steps=canonicalBlock.split(/\n      - /).slice(1);for(const step of steps.filter(s=>/run:/.test(s)&&!s.startsWith('name: Verify registered'))){assert.match(step,/working-directory: target\/simgolf-lite/);}
 assert.equal(canonicalBlock.split('-- node scripts/zk682-run-resource-growth.mjs').length-1,1);assert.match(canonicalBlock,/e2e\/zk682-resource-growth\.e2e\.ts --workers=1 --retries=0 --list/);assert.ok(canonicalBlock.indexOf('Linux supervisor capability smoke')<canonicalBlock.indexOf('Discover exactly one'));assert.ok(canonicalBlock.indexOf('Upload explicit bounded')<canonicalBlock.indexOf('Require actual exit zero'));
 const source=canonicalBlock.split('# BEGIN CANONICAL CONTROLLER')[1].split('# END CANONICAL CONTROLLER')[0];assert.doesNotMatch(source,/GITHUB_ENV[^\n]*GITHUB_SHA|GITHUB_SHA[^\n]*GITHUB_ENV/);assert.match(source,/VERIFIED_TARGET_SHA=/);assert.match(canonicalBlock,/env GITHUB_SHA="\$VERIFIED_TARGET_SHA" VITE_COMMIT_SHA="\$VERIFIED_TARGET_SHA" ZK682_EXPECTED_COMMIT="\$VERIFIED_TARGET_SHA" python3 "\$DRIVER_SUPERVISOR"/);
});
test('extracted canonical identity controller executes separate real Git fixtures and owned aliases',async()=>{
 const c=await embeddedCanonical('CONTROLLER','ZK682_CANONICAL_CONTROLLER_TEST'),root=mkdtempSync(join(tmpdir(),'zk682-canonical-git-'));
 const make=name=>{const repo=join(root,name);mkdirSync(repo);const git=(...args)=>execFileSync('git',args,{cwd:repo,encoding:'utf8',timeout:10000,maxBuffer:65536}).trim();git('init');git('config','user.email','fixture@example.invalid');git('config','user.name','Fixture');writeFileSync(join(repo,'identity'),name);git('add','.');git('commit','-m',name);return {repo,git,sha:git('rev-parse','HEAD')};};
 try{const driver=make('driver'),target=make('target'),identity=c.verifyCheckouts(driver.repo,target.repo,target.sha,driver.sha);assert.equal(identity.targetCommit,target.sha);assert.equal(identity.driverCommit,driver.sha);
 const aliases=c.childAliases(identity);const child=JSON.parse(execFileSync(process.execPath,['-e','console.log(JSON.stringify([process.env.GITHUB_SHA,process.env.VITE_COMMIT_SHA,process.env.ZK682_EXPECTED_COMMIT]))'],{cwd:target.repo,env:{...process.env,...aliases},encoding:'utf8',timeout:10000,maxBuffer:65536}));assert.deepEqual(child,[target.sha,target.sha,target.sha]);
 for(const invalid of [undefined,'HEAD',target.sha.slice(0,8),'0'.repeat(40)])assert.throws(()=>c.verifyCheckouts(driver.repo,target.repo,invalid,driver.sha));assert.throws(()=>c.verifyCheckouts(driver.repo,target.repo,target.sha,'0'.repeat(40)));assert.throws(()=>c.verifyCheckouts(driver.repo,driver.repo,driver.sha,driver.sha));assert.throws(()=>c.verifyCheckouts(driver.repo,join(target.repo,'missing'),target.sha,driver.sha));
 for(const key of Object.keys(aliases))assert.throws(()=>c.childAliases(identity,{[key]:driver.sha}));assert.deepEqual(c.childAliases(identity,aliases),aliases);
 writeFileSync(join(target.repo,'untracked'),'dirty');assert.throws(()=>c.verifyCheckouts(driver.repo,target.repo,target.sha,driver.sha));rmSync(join(target.repo,'untracked'));symlinkSync(target.repo,join(root,'alias'));assert.throws(()=>c.verifyCheckouts(target.repo,join(root,'alias'),target.sha,target.sha));
 }finally{rmSync(root,{recursive:true,force:true});}
});
test('canonical pins prove actual registered producer/helper/package/config parity without execution',async()=>{
 const c=await embeddedCanonical('CONTROLLER','ZK682_CANONICAL_CONTROLLER_TEST');const root=process.env.ZK682_CANONICAL_SOURCE_ROOT;assert.ok(root,'root controls must supply immutable target app-root ZK682_CANONICAL_SOURCE_ROOT');const rows=c.verifyPins(resolve(root));assert.equal(rows.length,Object.keys(c.targetPins).length);assert.equal(c.targetPins['e2e/zk682-resource-growth.e2e.ts'],'69cf83d45ab294d018e142b15834353105aaf456875f2320a0bce4d7fdc057f7');
 const wrapper=readFileSync(join(root,'scripts/zk682-run-resource-growth.mjs'),'utf8');assert.match(wrapper,/"e2e\/zk682-resource-growth\.e2e\.ts",\n    "--workers=1",\n    "--retries=0"/);assert.match(wrapper,/candidateCommit !== gitHead\.stdout\.trim\(\)/);assert.match(readFileSync(join(root,'e2e/zk682-resource-growth.e2e.ts'),'utf8'),/test\.slow\(\)/);assert.match(readFileSync(join(root,'playwright.config.ts'),'utf8'),/timeout: 600_000/);
 const fixture=realpathSync(mkdtempSync(join(tmpdir(),'zk682-canonical-pin-')));try{writeFileSync(join(fixture,'sample'),'base');const pins={sample:c.hash(Buffer.from('base'))};c.verifyPins(fixture,pins);writeFileSync(join(fixture,'sample'),'changed');assert.throws(()=>c.verifyPins(fixture,pins));rmSync(join(fixture,'sample'));symlinkSync(join(root,'package.json'),join(fixture,'sample'));assert.throws(()=>c.verifyPins(fixture,pins));}finally{rmSync(fixture,{recursive:true,force:true});}
});
test('extracted canonical artifact controller rejects empty completeness, missing, duplicate, symlink, oversize and unknown artifacts',async()=>{
 const c=await embeddedCanonical('BOUNDS','ZK682_CANONICAL_BOUNDS_TEST'),root=realpathSync(mkdtempSync(join(tmpdir(),'zk682-canonical-art-')));try{
 assert.equal(c.validateBounds(root),0);assert.throws(()=>c.validateBounds(root,Object.keys(c.artifactLimits),true));for(const name of ['unknown.json','__proto__','constructor'])assert.throws(()=>c.boundedArtifact(root,name));assert.throws(()=>c.validateBounds(root,['run/stdout.log','run/stdout.log']));
 mkdirSync(join(root,'run'));writeFileSync(join(root,'run/renderer-resource-growth.json'),'{}');assert.equal(c.boundedArtifact(root,'run/renderer-resource-growth.json'),2);writeFileSync(join(root,'run/renderer-resource-growth.json'),Buffer.alloc(65537));assert.throws(()=>c.validateBounds(root));rmSync(join(root,'run/renderer-resource-growth.json'));
 symlinkSync('/tmp',join(root,'run/stdout.log'));assert.throws(()=>c.validateBounds(root));rmSync(join(root,'run/stdout.log'));writeFileSync(join(root,'run/unexpected.json'),'{}');assert.throws(()=>c.validateBounds(root));rmSync(join(root,'run/unexpected.json'));
 writeFileSync(join(root,'run/stdout.log'),Buffer.alloc(262144));writeFileSync(join(root,'run/stderr.log'),'x');assert.throws(()=>c.validateBounds(root));rmSync(join(root,'run/stdout.log'));rmSync(join(root,'run/stderr.log'));
 writeFileSync(join(root,'run/zk682-resource-growth-final.png'),Buffer.alloc(1048577));assert.throws(()=>c.validateBounds(root));writeFileSync(join(root,'run/zk682-resource-growth-final.png'),Buffer.alloc(1048500));writeFileSync(join(root,'run/renderer-resource-growth.json'),Buffer.alloc(100));assert.throws(()=>c.validateBounds(root));assert.throws(()=>c.verifyInventory({artifacts:[]},root));
 assert.equal(c.artifactLimits['run/owned-command-receipt.json'],65536);assert.ok(c.required.includes('run/renderer-resource-growth-command.json'));assert.ok(c.required.includes('run/zk682-canvas-capture-receipt.json'));const upload=canonicalBlock.split('          path: |\n')[1].split('          if-no-files-found:')[0].trim().split('\n').map(l=>l.trim());assert.deepEqual(upload,Object.keys(c.artifactLimits).map(name=>'target/simgolf-lite/artifacts/canonical-renderer-verification/'+name));
 }finally{rmSync(root,{recursive:true,force:true});}
});

test('N canonical exacteebb controller rejects stale target and H or consumer pins missing source',async()=>{const c=await embeddedCanonical('CONTROLLER','ZK682_CANONICAL_CONTROLLER_TEST'),b=await embeddedCanonical('BOUNDS','ZK682_CANONICAL_BOUNDS_TEST'),actual=resolve(process.env.ZK682_CANONICAL_SOURCE_ROOT);assert.equal(c.targetCandidate,'eebb5a388a153078046021a64aa897a3886bc9f4');assert.equal(Object.keys(c.targetPins).length,21);assert.deepEqual(c.targetPins,b.expectedTargetPins);assert.equal(c.targetPins['scripts/zk682-public-canvas-capture.mjs'],'4e187ebcb7cd889e843aa1a994be0d5deeaa9e2aad5bed710b15da981bc665fc');assert.equal(c.targetPins['scripts/zk682-public-canvas-capture.test.mjs'],'33c5aa2092503116cf00f831d4c21d425f60db6b8b75cc24fac449ede5b591a4');assert.equal(c.targetPins['scripts/zk682-certification-contract.test.mjs'],'9d0fa57d16b887a77ea27ba67b5f1d6cc1a07c55b12ba2a0ca17eaf43cbc7ce8');c.verifyPins(actual);for(const target of ['4a27e748957925ac476e98e9aaeed4e6a70f095f','85787941a8bc2726cf57e02be86009d366c8bf26','f822040144de80314f1eb61a7de26f2bac7f3764'])assert.throws(()=>c.prepare('/unused-driver','/unused-target',target,'d'.repeat(40)));for(const [name,pin]of [['scripts/zk682-public-canvas-capture.mjs','d5895ff55f30850b0efa4f7c0b5d249cd03ae984361a2c366429ff6691f0717e'],['scripts/zk682-public-canvas-capture.test.mjs','471ce6fe836a3bae6af35bee3ef308e3465a9a23f261ce54dce666cf2d748737'],['scripts/zk682-certification-contract.test.mjs','c12e23188eaa50868f2fb36373885c2efc0e07a50ff3ec0d6527ceb2de411a52']])assert.throws(()=>c.verifyPins(actual,{...c.targetPins,[name]:pin}));const root=realpathSync(mkdtempSync(join(tmpdir(),'zk682-N-pins-')));try{for(const name of Object.keys(c.targetPins)){mkdirSync(dirname(join(root,name)),{recursive:true});writeFileSync(join(root,name),readFileSync(join(actual,name)));}c.verifyPins(root);for(const name of ['scripts/zk682-public-canvas-capture.mjs','scripts/zk682-public-canvas-capture.test.mjs','scripts/zk682-certification-contract.test.mjs']){const file=join(root,name),bytes=readFileSync(file);rmSync(file);assert.throws(()=>c.verifyPins(root));writeFileSync(file,Buffer.concat([bytes,Buffer.from('\n')]));assert.throws(()=>c.verifyPins(root));rmSync(file);symlinkSync(join(actual,name),file);assert.throws(()=>c.verifyPins(root));rmSync(file);writeFileSync(file,bytes);}c.verifyPins(root);}finally{rmSync(root,{recursive:true,force:true});}});
test('N canonical helper16 consumer6 policy6 and Chromium precede smoke discovery and sole wrapper',()=>{const commands=['node --test scripts/zk682-public-canvas-capture.test.mjs',"node --test --test-name-pattern='renderer completeness|renderer PNG|renderer public CDP|renderer consumer' scripts/zk682-certification-contract.test.mjs",'node --test scripts/zk682-resource-growth-recording-policy.test.mjs','npx playwright install --with-deps chromium','Linux supervisor capability smoke','Discover exactly one original canonical test without browser','-- node scripts/zk682-run-resource-growth.mjs --expected-commit'];const validate=block=>{let previous=-1;for(const command of commands){assert.equal(block.split(command).length-1,1,'one required control '+command);const position=block.indexOf(command);assert.ok(position>previous,'required control order');previous=position;}};validate(canonicalBlock);for(const command of commands.slice(0,4)){assert.throws(()=>validate(canonicalBlock.replace(command,'removed control')));assert.throws(()=>validate(canonicalBlock+'\n'+command));}const [helper,consumer]=commands;assert.throws(()=>validate(canonicalBlock.replace(helper,'F_SWAP').replace(consumer,helper).replace('F_SWAP',consumer)));const consumerSource=readFileSync(resolve(process.env.ZK682_CANONICAL_SOURCE_ROOT,'scripts/zk682-certification-contract.test.mjs'),'utf8');const selected=[...consumerSource.matchAll(/^test\(["']([^"']+)["']/gm)].map(match=>match[1]).filter(name=>/renderer completeness|renderer PNG|renderer public CDP|renderer consumer/.test(name));assert.equal(selected.length,6);assert.equal(readFileSync(resolve(process.env.ZK682_CANONICAL_SOURCE_ROOT,'scripts/zk682-public-canvas-capture.test.mjs'),'utf8').match(/^test\(/gm).length,16);assert.equal(readFileSync(resolve(process.env.ZK682_CANONICAL_SOURCE_ROOT,'scripts/zk682-resource-growth-recording-policy.test.mjs'),'utf8').match(/^test\(/gm).length,6);});

test('N full d144 workflow inverse preserves I and35f7 routing artifacts aliases and budgets byteexact',()=>{let inverse=workflow;const retargetEdits=[["4a27e748957925ac476e98e9aaeed4e6a70f095f","eebb5a388a153078046021a64aa897a3886bc9f4",2],["c12e23188eaa50868f2fb36373885c2efc0e07a50ff3ec0d6527ceb2de411a52","9d0fa57d16b887a77ea27ba67b5f1d6cc1a07c55b12ba2a0ca17eaf43cbc7ce8",2]];for(const [before,after,count]of [...retargetEdits].reverse()){assert.equal(inverse.split(after).length-1,count);inverse=inverse.split(after).join(before);}assert.equal(createHash('sha256').update(inverse).digest('hex'),'e09dd1788412ee78e1d709d992abcfcea227feb8e43e2798a54103037c2d9231');if(process.env.ZK682_N_DONOR_WORKFLOW)assert.equal(inverse,readFileSync(process.env.ZK682_N_DONOR_WORKFLOW,'utf8'));const edits=[["85787941a8bc2726cf57e02be86009d366c8bf26","4a27e748957925ac476e98e9aaeed4e6a70f095f",2],["d5895ff55f30850b0efa4f7c0b5d249cd03ae984361a2c366429ff6691f0717e","4e187ebcb7cd889e843aa1a994be0d5deeaa9e2aad5bed710b15da981bc665fc",2],["471ce6fe836a3bae6af35bee3ef308e3465a9a23f261ce54dce666cf2d748737","33c5aa2092503116cf00f831d4c21d425f60db6b8b75cc24fac449ede5b591a4",2],["Run ten canonical public CDP helper controls","Run sixteen canonical main-world public CDP helper controls",1]];for(const [before,after,count]of [...edits].reverse()){assert.equal(inverse.split(after).length-1,count);inverse=inverse.split(after).join(before);}assert.equal(createHash('sha256').update(inverse).digest('hex'),'2d99227441791631c68978d5db50b5e62a0aa2ec889f99fa307d188abd2c7492');assert.equal(workflow.slice(0,workflow.indexOf('\n  canonical-renderer-verification:\n')),inverse.slice(0,inverse.indexOf('\n  canonical-renderer-verification:\n')));assert.match(canonicalBlock,/Run sixteen canonical main-world public CDP helper controls/);assert.equal(canonicalBlock.split('node --test scripts\/zk682-public-canvas-capture.test.mjs').length-1,1);});

// BEGIN CURRENT CAPTURE P TESTS
const P_READER_SOURCE="const currentCaptureWorkflow = readFileSync(workflowPath, \"utf8\");\nfunction inverseCurrentCaptureWorkflow(source) { const marker=\"\\n  current-capture-phase-eebb:\\n\",choice=\"          - current-capture-phase-eebb\\n\";assert.equal(source.split(marker).length-1,1);assert.equal(source.split(choice).length-1,1);return source.slice(0,source.indexOf(marker)).replace(choice,\"\"); }\nconst workflow = inverseCurrentCaptureWorkflow(currentCaptureWorkflow);";
function embeddedCurrentCapture(marker){const block=currentCaptureWorkflow.split(`# BEGIN CURRENT CAPTURE ${marker}\n`)[1].split(`# END CURRENT CAPTURE ${marker}`)[0],code=block.split("node --input-type=module <<'NODE'\n")[1].split('\n          NODE')[0].split('\n').map(line=>line.slice(10)).join('\n');process.env[marker==='CONTROLLER'?'ZK682_CURRENT_CAPTURE_CONTROLLER_TEST':'ZK682_CURRENT_CAPTURE_BOUNDS_TEST']='1';return import('data:text/javascript,'+encodeURIComponent(code));}
const currentCaptureBlock=currentCaptureWorkflow.slice(currentCaptureWorkflow.indexOf('\n  current-capture-phase-eebb:\n'));

test('P exclusive routing and complete N workflow/test inverse preserve every old job',()=>{
 const text=currentCaptureWorkflow.split('\njobs:\n')[1],ids=['linux-evidence','native-evidence','aggregate','renderer-diagnostic','startup-diagnostic','renderer-recording-ablation','canonical-renderer-verification','current-capture-phase-eebb'];
 const active=mode=>ids.filter(id=>{const body=text.slice(text.indexOf(`  ${id}:\n`)),expression=body.match(/if: \$\{\{ (.*?) \}\}/)[1];return Function('inputs',`return (${expression});`)({mode});});
 assert.deepEqual(active(undefined),ids.slice(0,3));assert.deepEqual(active('certification'),ids.slice(0,3));for(const mode of ids.slice(3))assert.deepEqual(active(mode),[mode]);assert.deepEqual(active('unknown'),[]);
 assert.equal(createHash('sha256').update(inverseCurrentCaptureWorkflow(currentCaptureWorkflow)).digest('hex'),'be2f5f05db99c3ae450eceb2db6775362c8fe7c3b5098ebac6b7317c7912689d');assert.equal(workflow,inverseCurrentCaptureWorkflow(currentCaptureWorkflow));
 let inverse=readFileSync(fileURLToPath(import.meta.url),'utf8');inverse=inverse.slice(0,inverse.indexOf('\n// BEGIN CURRENT CAPTURE P TESTS'));inverse=inverse.replace(P_READER_SOURCE,'const workflow = readFileSync(workflowPath, "utf8");');inverse=inverse.replace('symlinkSync, realpathSync, lstatSync, renameSync','symlinkSync, realpathSync');assert.equal(createHash('sha256').update(inverse).digest('hex'),'dedc03fe2dd04c1284b5166f862637ad9cc6c78a9d5477db2cf408444f513c99');
 assert.throws(()=>inverseCurrentCaptureWorkflow(currentCaptureWorkflow+'\n  current-capture-phase-eebb:\n'));assert.throws(()=>inverseCurrentCaptureWorkflow(currentCaptureWorkflow.replace('          - current-capture-phase-eebb\n','')));
});

test('P direct command, immutable O pins and prerequisite ordering preserve finite original protocol',async()=>{
 const c=await embeddedCurrentCapture('CONTROLLER'),b=await embeddedCurrentCapture('BOUNDS');assert.equal(c.targetCandidate,'eebb5a388a153078046021a64aa897a3886bc9f4');assert.equal(Object.keys(c.targetPins).length,21);assert.equal(Object.keys(c.observerPins).length,4);assert.equal(c.appPin,'6ba5256282315022e45e1fba5f3b1377c27e95f152fbb3ea0c3414bb5ddc88b0');assert.deepEqual(c.artifactLimits,b.artifactLimits);
 const identity={targetCommit:c.targetCandidate,driverCommit:'d'.repeat(40),driverRoot:'/driver'};assert.deepEqual(c.diagnosticCommand(identity),['env','GITHUB_SHA='+c.targetCandidate,'VITE_COMMIT_SHA='+c.targetCandidate,'ZK682_EXPECTED_COMMIT='+c.targetCandidate,'python3','/driver/simgolf-lite/scripts/linux-diagnostic-supervisor.py','--out','artifacts/current-capture-phase-eebb/run','--seconds','1850','--parent-seconds','1910','--artifact-cap','1048576','--','npx','playwright','test','--config','playwright.zk682-current-capture-phase.generated.config.ts','e2e/zk682-current-capture-phase.generated.ts','--workers=1','--retries=0']);
 assert.equal(currentCaptureBlock.split('-- npx playwright test ').length-1,1);assert.doesNotMatch(currentCaptureBlock,/-- node scripts\/zk682-run-resource-growth\.mjs|continue-on-error|needs:/);assert.match(currentCaptureBlock,/timeout-minutes: 40/);assert.match(currentCaptureBlock,/source\/generated-provenance\.json/);assert.doesNotMatch(currentCaptureBlock,/renderer-resource-growth-command\.json/);
 const names=['Run twenty-four accepted O actual helper and producer controls','Run sixteen unchanged current H helper controls','Run six unchanged renderer consumer controls','Run six unchanged recording policy controls','Install target Chromium','Linux owned supervisor capability smoke','Discover exactly one derived test without browser','Run one derived direct Playwright diagnostic with target aliases','Bound finite partial artifacts','Upload explicit bounded','Retire only owned generated','Require valid current diagnostic'];let previous=-1;for(const name of names){assert.equal(currentCaptureBlock.split(name).length-1,1);const position=currentCaptureBlock.indexOf(name);assert.ok(position>previous);previous=position;}
 for(const key of ['GITHUB_SHA','VITE_COMMIT_SHA','ZK682_EXPECTED_COMMIT'])assert.throws(()=>c.childAliases(identity,{[key]:identity.driverCommit}));assert.deepEqual(c.childAliases(identity,c.childAliases(identity)),c.childAliases(identity));for(const stale of ['4a27e748957925ac476e98e9aaeed4e6a70f095f','0'.repeat(40),undefined])assert.throws(()=>c.assertRegisteredTarget(stale));
});

test('P config exact inverse keeps source-root webServer, devices, flags, recording and timeout',async()=>{
 const c=await embeddedCurrentCapture('CONTROLLER'),root=resolve(process.env.ZK682_CANONICAL_SOURCE_ROOT),before=readFileSync(join(root,'playwright.config.ts'),'utf8'),after=c.transformConfig(before);assert.equal(c.inverseConfig(after),before);assert.match(after,/testDir: "\.\/e2e"/);assert.match(after,/testMatch: "zk682-current-capture-phase\.generated\.ts"/);assert.match(after,/timeout: 600_000/);assert.match(after,/devices\["Desktop Chrome"\]/);assert.match(after,/trace: "retain-on-failure"/);assert.match(after,/command: "npm run dev -- --configLoader runner --mode e2e --host 127\.0\.0\.1 --port 4174"/);
 assert.doesNotMatch(c.generatedPaths[1],/\.e2e\.ts$/);assert.equal(resolve(root,dirname(c.generatedPaths[1])),resolve(root,'./e2e'));assert.equal(dirname(resolve(root,c.generatedPaths[2])),root);
 for(const [beforeAnchor,afterAnchor]of c.configEdits){assert.throws(()=>c.transformConfig(before.replace(beforeAnchor,'')));assert.throws(()=>c.transformConfig(before+beforeAnchor));assert.throws(()=>c.inverseConfig(after+afterAnchor));}assert.throws(()=>c.transformConfig(before.replace('timeout: 600_000','timeout: 600_001')));
});

test('P actual two Git fixture prepare after driver commit stages and guards correct roots and owned aliases',async()=>{
 const c=await embeddedCurrentCapture('CONTROLLER'),fixtureRoot=realpathSync(mkdtempSync(join(tmpdir(),'zk682-P-prepare-'))),source=resolve(process.env.ZK682_CANONICAL_SOURCE_ROOT),driverApp=resolve(dirname(fileURLToPath(import.meta.url)),'..');
 const init=repo=>{mkdirSync(repo,{recursive:true});const git=(...args)=>execFileSync('git',['-C',repo,...args],{encoding:'utf8',timeout:10000,maxBuffer:65536}).trim();git('init');git('config','user.email','fixture@example.invalid');git('config','user.name','Fixture');return git;};
 const copy=(from,to)=>{mkdirSync(dirname(to),{recursive:true});writeFileSync(to,readFileSync(from));};
 try{for(const nested of [false,true]){
  const driverRoot=join(fixtureRoot,nested?'nested-driver':'separate-driver'),driverGit=init(driverRoot);
  for(const path of Object.keys(c.observerPins))copy(join(driverApp,path),join(driverRoot,'simgolf-lite',path));copy(join(driverApp,'scripts/linux-diagnostic-supervisor.py'),join(driverRoot,'simgolf-lite/scripts/linux-diagnostic-supervisor.py'));copy(workflowPath,join(driverRoot,'.github/workflows/zk682-certification.yml'));driverGit('add','.');driverGit('commit','-m','committed exact observer driver');const driverSha=driverGit('rev-parse','HEAD');
  const targetRoot=nested?join(driverRoot,'target'):join(fixtureRoot,'separate-target'),targetGit=init(targetRoot),appRoot=join(targetRoot,'simgolf-lite');for(const path of [...Object.keys(c.targetPins),'src/App.tsx'])copy(join(source,path),join(appRoot,path));targetGit('add','.');targetGit('commit','-m','source-pinned target fixture');const targetSha=targetGit('rev-parse','HEAD');
  assert.throws(()=>c.assertRegisteredTarget(targetSha));await assert.rejects(c.prepare(driverRoot,targetRoot,targetSha,driverSha));const prepared=await c.prepare(driverRoot,targetRoot,targetSha,driverSha,{fixture:true}),proof=await c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared});
  assert.deepEqual(proof.provenance.generated.map(row=>row.path),c.generatedPaths);assert.equal(proof.provenance.canonicalCommandReceiptExpected,false);assert.equal(proof.provenance.ledgerBasename,'zk682-current-capture-phase-eebb-diagnostic.json');assert.equal(proof.provenance.observerImport,new URL('simgolf-lite/scripts/zk682-current-capture-phase/capture.mjs',pathToRootURL(driverRoot)).href);
  const helper=readFileSync(join(appRoot,c.generatedPaths[0]),'utf8');assert.ok(helper.includes(JSON.stringify(proof.provenance.observerImport)));assert.equal(proof.modules.capture.inverseCaptureSource(helper),readFileSync(join(source,'scripts/zk682-public-canvas-capture.mjs'),'utf8'));assert.equal(proof.modules.producer.inverseProducerSource(readFileSync(join(appRoot,c.generatedPaths[1]),'utf8')),readFileSync(join(source,'e2e/zk682-resource-growth.e2e.ts'),'utf8'));assert.equal(c.inverseConfig(readFileSync(join(appRoot,c.generatedPaths[2]),'utf8')),readFileSync(join(source,'playwright.config.ts'),'utf8'));
  assert.equal(targetGit('diff','--exit-code','HEAD','--'),'');assert.equal(driverGit('diff','--exit-code','HEAD','--'),'');assert.equal(c.verifyPins(appRoot).length,21);assert.equal(c.verifyPins(appRoot,{'src/App.tsx':c.appPin}).length,1);
  const aliases=c.childAliases(prepared),child=JSON.parse(execFileSync(process.execPath,['-e','console.log(JSON.stringify({cwd:process.cwd(),github:process.env.GITHUB_SHA,vite:process.env.VITE_COMMIT_SHA,expected:process.env.ZK682_EXPECTED_COMMIT}))'],{cwd:appRoot,env:{...process.env,...aliases},encoding:'utf8',timeout:10000,maxBuffer:65536}));assert.deepEqual(child,{cwd:appRoot,github:targetSha,vite:targetSha,expected:targetSha});
  assert.throws(()=>c.stage(appRoot,c.generatedPaths[0],helper));await assert.rejects(c.prepare(driverRoot,targetRoot,targetSha,driverSha,{fixture:true}));await assert.rejects(c.verifyPrepared(driverRoot,appRoot,targetSha,driverSha,{fixture:true,...prepared}));await assert.rejects(c.verifyPrepared(driverRoot,targetRoot,targetSha,'0'.repeat(40),{fixture:true,...prepared}));assert.throws(()=>c.verifyCheckouts(driverRoot,driverRoot,driverSha,driverSha));
  const appFile=join(appRoot,'src/App.tsx'),appBytes=readFileSync(appFile);writeFileSync(appFile,Buffer.concat([appBytes,Buffer.from('\n')]));await assert.rejects(c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared}));writeFileSync(appFile,appBytes);
  const configFile=join(appRoot,c.generatedPaths[2]),configBytes=readFileSync(configFile);writeFileSync(configFile,Buffer.concat([configBytes,Buffer.from('\n')]));await assert.rejects(c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared}));writeFileSync(configFile,configBytes);
  writeFileSync(join(appRoot,'unowned'),'foreign');await assert.rejects(c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared}));rmSync(join(appRoot,'unowned'));
  // Synthetic terminal receipt exercises only source-control behavior; no workload is launched.
  const runRoot=join(appRoot,c.namespace,'run'),reporterRoot=join(appRoot,'playwright-report');mkdirSync(runRoot);mkdirSync(reporterRoot);writeFileSync(join(reporterRoot,'index.html'),'control-only original reporter output');
  const synthetic={command:c.directArguments(),workerSeconds:1850,parentSeconds:1910,closureVerified:true,childReaped:true,ownedStillObserved:[],ownedZombiesStillObserved:[]};writeFileSync(join(runRoot,'owned-command-receipt.json'),JSON.stringify(synthetic));
  await assert.rejects(c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared}));const after=await c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared,postSettlement:true});assert.match(after.sourceQualification,/no blanket untracked cleanliness claim/);assert.equal(readFileSync(join(reporterRoot,'index.html'),'utf8'),'control-only original reporter output');
  writeFileSync(appFile,Buffer.concat([appBytes,Buffer.from('\n')]));await assert.rejects(c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared,postSettlement:true}));writeFileSync(appFile,appBytes);
  writeFileSync(join(runRoot,'owned-command-receipt.json'),JSON.stringify({...synthetic,closureVerified:false}));await assert.rejects(c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared,postSettlement:true}));rmSync(reporterRoot,{recursive:true});rmSync(runRoot,{recursive:true});
  symlinkSync(targetRoot,join(fixtureRoot,nested?'nested-alias':'separate-alias'));assert.throws(()=>c.verifyCheckouts(driverRoot,join(fixtureRoot,nested?'nested-alias':'separate-alias'),targetSha,driverSha));
  const scripts=join(appRoot,'scripts'),scriptsSaved=join(appRoot,'saved-scripts');renameSync(scripts,scriptsSaved);symlinkSync(scriptsSaved,scripts);assert.throws(()=>c.verifyPins(appRoot));rmSync(scripts);renameSync(scriptsSaved,scripts);
  await c.verifyPrepared(driverRoot,targetRoot,targetSha,driverSha,{fixture:true,...prepared});const owned=proof.provenance.generated;
  assert.throws(()=>c.retireGenerated(appRoot,owned,{closureVerified:false}));assert.ok(owned.every(row=>lstatSync(join(appRoot,row.path)).isFile()));
  const ownedFile=join(appRoot,owned[0].path),saved=join(fixtureRoot,nested?'nested-original-helper':'separate-original-helper');renameSync(ownedFile,saved);writeFileSync(ownedFile,'foreign replacement');assert.throws(()=>c.retireGenerated(appRoot,owned,null));assert.equal(readFileSync(ownedFile,'utf8'),'foreign replacement');assert.ok(owned.slice(1).every(row=>lstatSync(join(appRoot,row.path)).isFile()));rmSync(ownedFile);renameSync(saved,ownedFile);
  c.retireGenerated(appRoot,owned,null);for(const row of owned)assert.equal(lstatSync(join(appRoot,row.path),{throwIfNoEntry:false}),undefined);assert.equal(targetGit('diff','--exit-code','HEAD','--'),'');
 }}finally{rmSync(fixtureRoot,{recursive:true,force:true});}
});
function pathToRootURL(root){return new URL('file://'+root+'/');}

test('P strict finite artifact/ledger bounds and forward reverse actual inventory refuse unsafe partial inputs',async()=>{
 const c=await embeddedCurrentCapture('CONTROLLER'),b=await embeddedCurrentCapture('BOUNDS'),root=realpathSync(mkdtempSync(join(tmpdir(),'zk682-P-art-')));
 try{
  assert.equal(b.validateBounds(root),0);assert.deepEqual(await b.assessPresent(root,'/unused',c,{}),{diagnosticReady:false,phase:'UNKNOWN',qualification:'Ledger file absent; not reached or unknown, no fabricated stdout payload'});
  for(const name of ['unknown','__proto__','run/renderer-resource-growth-command.json','run/../source/identity.json'])assert.throws(()=>b.boundedArtifact(root,name));assert.equal(b.artifactLimits['run/zk682-current-capture-phase-eebb-diagnostic.json'],8192);assert.equal(b.artifactLimits['source/generated-provenance.json'],65536);
  mkdirSync(join(root,'run'));const ledger=join(root,'run/zk682-current-capture-phase-eebb-diagnostic.json');writeFileSync(ledger,Buffer.alloc(8193));assert.throws(()=>b.validateBounds(root));rmSync(ledger);symlinkSync('/tmp',ledger);assert.throws(()=>b.validateBounds(root));rmSync(ledger);
  writeFileSync(join(root,'run/stdout.log'),'\u001b[31mPlaywright prefix\u001b[0m\n');writeFileSync(join(root,'run/stderr.log'),'');const rows=['stdout.log','stderr.log'].map(path=>{const bytes=readFileSync(join(root,'run',path));return {path,bytes:bytes.length,sha256:b.hash(bytes)};});b.verifyInventory({artifacts:rows},root,'run');assert.throws(()=>b.verifyInventory({artifacts:[rows[0],rows[0]]},root,'run'));assert.throws(()=>b.verifyInventory({artifacts:rows.slice(0,1)},root,'run'));assert.throws(()=>b.verifyInventory({artifacts:[{...rows[0],sha256:'0'.repeat(64)},rows[1]]},root,'run'));
  writeFileSync(join(root,'run/unknown.json'),'{}');assert.throws(()=>b.validateBounds(root));rmSync(join(root,'run/unknown.json'));writeFileSync(join(root,'run/stdout.log'),Buffer.alloc(262144));writeFileSync(join(root,'run/stderr.log'),'x');assert.throws(()=>b.validateBounds(root));rmSync(join(root,'run/stdout.log'));rmSync(join(root,'run/stderr.log'));
  writeFileSync(join(root,'run/zk682-resource-growth-final.png'),Buffer.alloc(1048577));assert.throws(()=>b.validateBounds(root));writeFileSync(join(root,'run/zk682-resource-growth-final.png'),Buffer.alloc(1048500));writeFileSync(join(root,'run/renderer-resource-growth.json'),Buffer.alloc(100));assert.throws(()=>b.validateBounds(root));rmSync(join(root,'run/zk682-resource-growth-final.png'));rmSync(join(root,'run/renderer-resource-growth.json'));
  const modules=await c.observerModules(resolve(dirname(fileURLToPath(import.meta.url)),'../..')),observer=modules.capture.createCaptureObserver({clock:()=>1});observer.enter('canvas-count');observer.end('canvas-count');const snapshot=observer.finish(false);writeFileSync(ledger,JSON.stringify(snapshot)+'\n');assert.ok(b.validateBounds(root)>0);const bad=structuredClone(snapshot);bad.rows[0].status='forged';writeFileSync(ledger,JSON.stringify(bad));await assert.rejects(b.assessPresent(root,'/unused',c,{modules}));
  const upload=currentCaptureBlock.split('          path: |\n')[1].split('          if-no-files-found:')[0].trim().split('\n').map(line=>line.trim());assert.deepEqual(upload,Object.keys(b.artifactLimits).map(name=>'target/simgolf-lite/artifacts/current-capture-phase-eebb/'+name));assert.match(currentCaptureBlock,/always\(\) && steps\.current_capture_artifact_bounds\.conclusion == 'success'/);
 }finally{rmSync(root,{recursive:true,force:true});}
});
// END CURRENT CAPTURE P TESTS

// BEGIN P DISCOVERY REPORTER CORRECTION TESTS
import {spawnSync} from 'node:child_process';
const pDiscoveryBaseline='/private/tmp/golf-eebb-current-capture-P-source-1';
const pDiscoveryDependencies=realpathSync(resolve(process.env.ZK682_P_DISCOVERY_DEPENDENCIES_ROOT||'/Users/zbkutlow/.codex/worktrees/startup-review-demand-eebb/golf-course-simulator-game/simgolf-lite/node_modules'));
const pDiscoveryDependencyPins=Object.freeze({'playwright/package.json':'6b840268612656f0639fb7d68782e8353bdf11518589d30ddf66f283c2670ed5','@playwright/test/package.json':'9d8556509e073169efec663b7f71c13f17d7002b307d00d48bf88ee91c387f3e','playwright-core/package.json':'759e376f995bf39edd4810d699b99469bab1d7428b6fbc78d41912f367df7ba9','playwright/cli.js':'5e79302a6aad7d835d92d5ae6b4244c91cf61b28e94d7917279090e6c231f7a1'});
const pDiscoveryHash=bytes=>createHash('sha256').update(bytes).digest('hex');
function pDiscoveryCommands(){const start='      - name: Discover exactly one derived test without browser\n',end='      - name: Run one derived direct Playwright diagnostic with target aliases\n';assert.equal(currentCaptureBlock.split(start).length-1,1);const step=currentCaptureBlock.split(start)[1].split(end)[0],line=step.split('\n').find(text=>text.includes('npx playwright test ')&&text.includes('--list'));assert(line);const args=line.split('npx playwright ')[1].split(' > ')[0].trim().split(' ');assert.equal(args.filter(arg=>arg==='--list').length,1);assert.equal(args.filter(arg=>arg==='--reporter=line').length,1);const gate=step.match(/grep -Eq '([^']+)' /);assert(gate);return {args,gate:gate[1]};}
function pDiscoveryCheckDependencies(){for(const [path,sha] of Object.entries(pDiscoveryDependencyPins)){const bytes=readFileSync(join(pDiscoveryDependencies,path));assert.equal(pDiscoveryHash(bytes),sha,'declared installed dependency '+path);if(path.endsWith('/package.json'))assert.equal(JSON.parse(bytes).version,'1.61.1');}return Object.fromEntries(Object.keys(pDiscoveryDependencyPins).map(path=>[path,pDiscoveryHash(readFileSync(join(pDiscoveryDependencies,path)))]));}
async function pDiscoveryFixture(t,label){const c=await embeddedCurrentCapture('CONTROLLER'),root=realpathSync(mkdtempSync(join(tmpdir(),'zk682-P-discovery-'+label+'-')));t.after(()=>rmSync(root,{recursive:true,force:true}));const driver=join(root,'driver'),target=join(driver,'target'),app=join(target,'simgolf-lite'),source=resolve(process.env.ZK682_CANONICAL_SOURCE_ROOT||'/Users/zbkutlow/.codex/worktrees/consumer-mainworld-fixture-4a27/golf-course-simulator-game/simgolf-lite'),driverApp=resolve(dirname(fileURLToPath(import.meta.url)),'..');
 const init=repo=>{mkdirSync(repo,{recursive:true});const git=(...args)=>execFileSync('git',['-C',repo,...args],{encoding:'utf8',timeout:10000,maxBuffer:65536}).trim();git('init','--quiet');git('config','user.email','fixture@example.invalid');git('config','user.name','Fixture');return git;};const copy=(from,to)=>{mkdirSync(dirname(to),{recursive:true});writeFileSync(to,readFileSync(from));};
 const driverGit=init(driver);for(const path of Object.keys(c.observerPins))copy(join(driverApp,path),join(driver,'simgolf-lite',path));copy(join(driverApp,'scripts/linux-diagnostic-supervisor.py'),join(driver,'simgolf-lite/scripts/linux-diagnostic-supervisor.py'));copy(workflowPath,join(driver,'.github/workflows/zk682-certification.yml'));driverGit('add','.');driverGit('commit','--quiet','-m','owned discovery driver');const driverSha=driverGit('rev-parse','HEAD');
 const targetGit=init(target);for(const path of [...Object.keys(c.targetPins),'src/App.tsx'])copy(join(source,path),join(app,path));writeFileSync(join(target,'.gitignore'),'/simgolf-lite/node_modules\n');targetGit('add','.');targetGit('commit','--quiet','-m','owned exact-byte discovery target');const targetSha=targetGit('rev-parse','HEAD');symlinkSync(pDiscoveryDependencies,join(app,'node_modules'),'dir');assert.equal(realpathSync(join(app,'node_modules')),pDiscoveryDependencies);assert.equal(targetGit('status','--porcelain','--untracked-files=all'),'');assert.equal(targetGit('check-ignore','simgolf-lite/node_modules'),'simgolf-lite/node_modules');
 const prepared=await c.prepare(driver,target,targetSha,driverSha,{fixture:true}),verify=()=>c.verifyPrepared(driver,target,targetSha,driverSha,{fixture:true,...prepared});await verify();const env={...process.env,...c.childAliases(prepared),CI:'true',PWTEST_CACHE_DIR:join(root,'transform-cache'),PLAYWRIGHT_HTML_OPEN:'never'};for(const key of Object.keys(env))if(/^PLAYWRIGHT_(HTML|JSON|JUNIT|BLOB)_/.test(key)&&key!=='PLAYWRIGHT_HTML_OPEN')delete env[key];delete env.PW_TEST_HTML_REPORT_OPEN;delete env.PLAYWRIGHT_LAST_RUN_OUTPUT_FILE;
 return {c,root,driver,target,app,targetGit,prepared,verify,env,run(args){assert(args.includes('--list'),'only real discovery, never producer execution');return spawnSync(process.execPath,[join(pDiscoveryDependencies,'playwright/cli.js'),...args],{cwd:app,env,encoding:'utf8',timeout:45000,maxBuffer:262144});}};
}
function pDiscoveryOne(result,gate){assert.equal(result.error,undefined);assert.equal(result.status,0,result.stderr);assert.equal(result.signal,null);assert.equal([...result.stdout.matchAll(/^Total: 1 test in 1 file$/gm)].length,1,result.stdout);assert.equal(spawnSync('grep',['-Eq',gate],{input:result.stdout,encoding:'utf8',timeout:10000,maxBuffer:65536}).status,0);}

test('P discovery correction is exactly one reporter literal and appended controls with immutable producer command',async()=>{const before=readFileSync(join(pDiscoveryBaseline,'zk682-certification.yml'),'utf8'),testsBefore=readFileSync(join(pDiscoveryBaseline,'zk682-workflow.test.mjs'),'utf8');assert.equal(pDiscoveryHash(before),'9a8531516f137843dee6b64d53dc57811ee9f83c38450c968a51cf5b45c00f7d');assert.equal(pDiscoveryHash(testsBefore),'25a25d6435aed41b3eff72cebe97ba314e25fbd18dd8b647d361ab3835b52d42');const old='--workers=1 --retries=0 --list > artifacts/current-capture-phase-eebb/source/discovery.log',updated='--workers=1 --retries=0 --list --reporter=line > artifacts/current-capture-phase-eebb/source/discovery.log';assert.equal(currentCaptureWorkflow.split(updated).length-1,1);assert.equal(currentCaptureWorkflow.replace(updated,old),before);const text=readFileSync(fileURLToPath(import.meta.url),'utf8'),boundary='\n// BEGIN P DISCOVERY REPORTER CORRECTION TESTS\n';assert.equal(text.split(boundary).length,2);assert.equal(text.slice(0,text.indexOf(boundary)),testsBefore);const c=await embeddedCurrentCapture('CONTROLLER'),{args}=pDiscoveryCommands();assert.deepEqual(args,[...c.directArguments().slice(2),'--list','--reporter=line']);const start='      - name: Run one derived direct Playwright diagnostic with target aliases\n',end='      - name: Bound finite partial artifacts and authoritative ledger file\n',body=source=>source.split(start)[1].split(end)[0];assert.equal(body(currentCaptureWorkflow),body(before));assert.deepEqual(c.directArguments(),['npx','playwright','test','--config','playwright.zk682-current-capture-phase.generated.config.ts','e2e/zk682-current-capture-phase.generated.ts','--workers=1','--retries=0']);assert.doesNotMatch(body(currentCaptureWorkflow),/--reporter|--list/);});

test('P discovery real installed Playwright lists one test and line reporter prevents HTML without weakening strict ownership',async t=>{const dependenciesBefore=pDiscoveryCheckDependencies(),{args,gate}=pDiscoveryCommands();for(const corrected of [false,true]){const f=await pDiscoveryFixture(t,corrected?'line':'baseline'),config=readFileSync(join(f.app,f.c.generatedPaths[2])),spec=readFileSync(join(f.app,f.c.generatedPaths[1])),argv=corrected?args:args.filter(arg=>arg!=='--reporter=line'),result=f.run(argv);pDiscoveryOne(result,gate);writeFileSync(join(f.app,f.c.namespace,'source/discovery.log'),result.stdout,{flag:'wx'});assert.deepEqual(readFileSync(join(f.app,f.c.generatedPaths[2])),config);assert.deepEqual(readFileSync(join(f.app,f.c.generatedPaths[1])),spec);assert.equal(f.targetGit('diff','--exit-code','HEAD','--'),'');const html=join(f.app,'playwright-report/index.html');if(!corrected){assert.ok(lstatSync(html).isFile(),'actual baseline --list must create HTML');assert.match(f.targetGit('status','--porcelain','--untracked-files=all'),/\?\? simgolf-lite\/playwright-report\/index\.html/);await assert.rejects(f.verify(),/unowned target dirt.*playwright-report\/index\.html/);}else{assert.equal(lstatSync(join(f.app,'playwright-report'),{throwIfNoEntry:false}),undefined);await f.verify();writeFileSync(join(f.app,'unowned-discovery-control.txt'),'declared arbitrary untracked fixture dirt');await assert.rejects(f.verify(),/unowned target dirt.*unowned-discovery-control\.txt/);assert.equal(readFileSync(join(f.app,'unowned-discovery-control.txt'),'utf8'),'declared arbitrary untracked fixture dirt');}}assert.deepEqual(pDiscoveryCheckDependencies(),dependenciesBefore);});

test('P discovery real CLI zero and duplicate test counts fail the unchanged workflow count gate',async t=>{pDiscoveryCheckDependencies();const {args,gate}=pDiscoveryCommands(),f=await pDiscoveryFixture(t,'count-negatives');const missing=f.run([...args,'--grep=^P_DISCOVERY_NO_SUCH_TEST$']);assert.equal(missing.error,undefined);assert.equal(missing.status,1,missing.stderr);assert.equal(missing.signal,null);assert.match(missing.stderr,/No tests found/);assert.equal(spawnSync('grep',['-Eq',gate],{input:missing.stdout,encoding:'utf8',timeout:10000,maxBuffer:65536}).status,1);const file=join(f.app,f.c.generatedPaths[1]);writeFileSync(file,readFileSync(file,'utf8')+'\ntest("P discovery duplicate count control only", () => { throw new Error("Discovery must not execute test bodies"); });\n');const duplicate=f.run(args);assert.equal(duplicate.error,undefined);assert.equal(duplicate.status,0,duplicate.stderr);assert.equal(duplicate.signal,null);assert.match(duplicate.stdout,/^Total: 2 tests in 1 file$/m);assert.equal(spawnSync('grep',['-Eq',gate],{input:duplicate.stdout,encoding:'utf8',timeout:10000,maxBuffer:65536}).status,1);assert.notEqual(pDiscoveryHash(readFileSync(file)),f.prepared.owners.find(row=>row.path===f.c.generatedPaths[1]).sha256);await assert.rejects(f.verify());});
// END P DISCOVERY REPORTER CORRECTION TESTS
