import assert from 'node:assert/strict';import test from 'node:test';import * as fs from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {deflateSync} from 'node:zlib';
import {captureVisibleCanvas,canvasClip,readCanvas,decodeStrictPng,strictBase64,crc32,sha256,PUBLIC_CDP_CAPTURE_METHOD} from './zk682-public-canvas-capture.mjs';
const state={current:true,connected:true,visible:true,tag:'CANVAS',x:0,y:0,width:2,height:1,viewportWidth:1280,viewportHeight:720,intrinsicWidth:2,intrinsicHeight:1,dpr:1,zoom:1};
const chunk=(name,data)=>{const size=Buffer.alloc(4);size.writeUInt32BE(data.length);const body=Buffer.concat([Buffer.from(name),data]),crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(body));return Buffer.concat([size,body,crc]);};
function png({blank=false,transparent=false}={}){const header=Buffer.alloc(13);header.writeUInt32BE(2,0);header.writeUInt32BE(1,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(Buffer.from([0,255,0,0,transparent?0:255,blank?255:0,0,blank?0:255,transparent?0:255]))),chunk('IEND',Buffer.alloc(0))]);}
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const clock=()=>{let now=0,fire;return {timing:{now:()=>now,set:(fn,ms)=>{assert.equal(ms,10000);fire=fn;return 1;},clear:()=>{}},elapse:()=>{now=10000;},expire:()=>{now=10000;fire();}};};
const tick=async()=>{for(let i=0;i<40;i++)await Promise.resolve();};
function fixture(options={}){let evaluations=0,detach=0,dispose=0,sent;const handle={evaluate:async()=>structuredClone(evaluations++?options.after??state:state),dispose:async()=>{dispose++;if(Object.hasOwn(options,'disposeError'))throw options.disposeError;}},session={send:async(method,args)=>{sent={method,args};if(Object.hasOwn(options,'primary'))throw options.primary;return options.sendPromise??{data:options.data??png().toString('base64')};},detach:async()=>{detach++;if(Object.hasOwn(options,'detachError'))throw options.detachError;return options.detachPromise;}};return {handle,session,page:{locator:()=>({count:async()=>options.count??1}),$:()=>options.handlePromise??Promise.resolve(handle),context:()=>({newCDPSession:()=>options.sessionPromise??Promise.resolve(session)})},stats:()=>({detach,dispose,sent})};}
function storage(){const root=fs.realpathSync(fs.mkdtempSync(join(tmpdir(),'zk682-canonical-cdp-')));return {root,path:join(root,'zk682-resource-growth-final.png'),cleanup:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('canonical integrated helper publishes current validated PNG and exact strict receipt after owned closure',async()=>{const s=storage(),f=fixture();try{const receipt=await captureVisibleCanvas(f.page,s.path);assert.deepEqual(Object.keys(receipt).sort(),['method','clip','before','after','bytes','sha256','qualification'].sort());assert.equal(receipt.method,PUBLIC_CDP_CAPTURE_METHOD);assert.equal(receipt.sha256,sha256(fs.readFileSync(s.path)));assert.deepEqual(fs.readdirSync(s.root),['zk682-resource-growth-final.png']);assert.deepEqual(f.stats().sent,{method:'Page.captureScreenshot',args:{format:'png',clip:{x:0,y:0,width:2,height:1,scale:1},fromSurface:true,captureBeyondViewport:false,optimizeForSpeed:false}});assert.deepEqual([f.stats().detach,f.stats().dispose],[1,1]);decodeStrictPng(fs.readFileSync(s.path),receipt.clip);}finally{s.cleanup();}});
test('canonical integrated helper preserves every falsy primary despite secondary cleanup and publishes nothing',async()=>{for(const primary of [undefined,null,false,0,'']){const s=storage(),f=fixture({primary,detachError:new Error('detach secondary'),disposeError:new Error('dispose secondary')});try{let rejected=false,actual;try{await captureVisibleCanvas(f.page,s.path);}catch(error){rejected=true;actual=error;}assert.equal(rejected,true);assert.equal(actual,primary);assert.deepEqual(fs.readdirSync(s.root),[]);assert.deepEqual([f.stats().detach,f.stats().dispose],[1,1]);}finally{s.cleanup();}}});
test('canonical integrated helper discards late capture result with no filesystem publication',async()=>{const s=storage(),c=clock(),pending=deferred(),f=fixture({sendPromise:pending.promise});try{const result=captureVisibleCanvas(f.page,s.path,{timing:c.timing});await tick();c.expire();await assert.rejects(result,/deadline10000ms/);pending.resolve({data:png().toString('base64')});await tick();assert.deepEqual(fs.readdirSync(s.root),[]);assert.deepEqual([f.stats().detach,f.stats().dispose],[1,1]);}finally{s.cleanup();}});
test('canonical integrated delayed monotonic acquisition owns handle and session before deadline assignment',async()=>{for(const acquisition of ['handle','session']){const s=storage(),c=clock(),pending=deferred(),f=fixture({[acquisition+'Promise']:pending.promise});try{const result=captureVisibleCanvas(f.page,s.path,{timing:c.timing});await tick();c.elapse();pending.resolve(f[acquisition]);await assert.rejects(result,/deadline10000ms/);await tick();assert.equal(f.stats().dispose,1);if(acquisition==='session')assert.equal(f.stats().detach,1);assert.deepEqual(fs.readdirSync(s.root),[]);}finally{s.cleanup();}}});
test('canonical integrated cleanup failure and pending detach deadline never publish final PNG',async()=>{for(const field of ['detachError','disposeError']){const s=storage(),primary=Symbol(field),f=fixture({[field]:primary});try{await assert.rejects(captureVisibleCanvas(f.page,s.path),error=>error===primary);assert.deepEqual([f.stats().detach,f.stats().dispose],[1,1]);assert.deepEqual(fs.readdirSync(s.root),[]);}finally{s.cleanup();}}const s=storage(),c=clock(),pending=deferred(),f=fixture({detachPromise:pending.promise});try{const result=captureVisibleCanvas(f.page,s.path,{timing:c.timing});await tick();c.expire();await assert.rejects(result,/deadline10000ms/);pending.resolve();await tick();assert.deepEqual(fs.readdirSync(s.root),[]);}finally{s.cleanup();}});
test('canonical publication refuses pre-existing file and symlink without deleting either',async()=>{for(const symlink of [false,true]){const s=storage(),sentinel=join(s.root,'sentinel');try{fs.writeFileSync(sentinel,'keep');if(symlink)fs.symlinkSync(sentinel,s.path);else fs.writeFileSync(s.path,'existing');await assert.rejects(captureVisibleCanvas(fixture().page,s.path),error=>error.code==='EEXIST');assert.equal(fs.readFileSync(s.path,'utf8'),symlink?'keep':'existing');assert.equal(fs.readFileSync(sentinel,'utf8'),'keep');assert.equal(fs.lstatSync(s.path).isSymbolicLink(),symlink);assert.ok(!fs.readdirSync(s.root).some(name=>name.includes('.cdp-pending-')));}finally{s.cleanup();}}});
test('canonical publication checks total deadline before promotion and rolls back late exclusive link',async()=>{for(const phase of ['write','link']){const s=storage(),c=clock();let links=0;const io={...fs,writeFileSync:(...args)=>{fs.writeFileSync(...args);if(phase==='write')c.elapse();},linkSync:(...args)=>{links++;fs.linkSync(...args);if(phase==='link')c.elapse();}};try{await assert.rejects(captureVisibleCanvas(fixture().page,s.path,{timing:c.timing,io}),/total capture\/publication deadline10000ms/);assert.equal(links,phase==='link'?1:0);assert.deepEqual(fs.readdirSync(s.root),[]);}finally{s.cleanup();}}});
test('canonical publication preserves falsy filesystem primary despite failed rollback cleanup',async()=>{for(const primary of [undefined,null,false,0,'']){const s=storage(),io={...fs,linkSync:()=>{throw primary;},unlinkSync:()=>{throw new Error('secondary rollback');}};try{let rejected=false,actual;try{await captureVisibleCanvas(fixture().page,s.path,{io});}catch(error){rejected=true;actual=error;}assert.equal(rejected,true);assert.equal(actual,primary);assert.equal(fs.existsSync(s.path),false);}finally{s.cleanup();}}});
test('canonical publication rollback deletes only its inode and preserves foreign replacements',async()=>{const s=storage(),c=clock(),io={...fs,linkSync:(temporary,final)=>{fs.linkSync(temporary,final);fs.unlinkSync(final);fs.writeFileSync(final,'foreign replacement');c.elapse();}};try{await assert.rejects(captureVisibleCanvas(fixture().page,s.path,{timing:c.timing,io}),/deadline10000ms/);assert.equal(fs.readFileSync(s.path,'utf8'),'foreign replacement');assert.deepEqual(fs.readdirSync(s.root),['zk682-resource-growth-final.png']);}finally{s.cleanup();}});
test('canonical strict base64 PNG decode and geometry reject malformed oversize blank stale duplicate inputs',async()=>{assert.throws(()=>strictBase64('A'.repeat(4*Math.ceil(1048576/3)+4)));for(const data of ['',png().toString('base64')+'\n','!!!!'])assert.throws(()=>strictBase64(data));for(const bytes of [png({blank:true}),png({transparent:true}),Buffer.alloc(0),Buffer.alloc(1048577)])assert.throws(()=>decodeStrictPng(bytes));const crc=Buffer.from(png());crc[crc.length-1]^=1;assert.throws(()=>decodeStrictPng(crc));for(const options of [{count:0},{count:2},{data:'!!!!'},{after:{...state,current:false}},{after:{...state,connected:false}},{after:{...state,visible:false}},{after:{...state,width:0}},{after:{...state,dpr:2}},{after:{...state,x:0.5}}]){const s=storage();try{await assert.rejects(captureVisibleCanvas(fixture(options).page,s.path));assert.deepEqual(fs.readdirSync(s.root),[]);}finally{s.cleanup();}}assert.deepEqual(canvasClip(state),{x:0,y:0,width:2,height:1});});
