import {beforeEach,afterEach,expect,it,vi} from 'vitest';
import * as PIXI from 'pixi.js';
let uid=9400;
function cleanup(...actions:(()=>void)[]){vi.restoreAllMocks();let failed=false,first:unknown;for(const action of actions)try{action();}catch(error){if(!failed){failed=true;first=error;}}if(failed)throw first;}
function host(){return new PIXI.GraphicsContextSystem({uid:++uid,limits:{maxBatchableTextures:16},gc:{now:0,addResourceHash:vi.fn()}} as unknown as ConstructorParameters<typeof PIXI.GraphicsContextSystem>[0]);}
function draw(texture:PIXI.Texture){const c=new PIXI.GraphicsContext();c.batchMode='no-batch';for(let i=0;i<200;i++)c.rect(i*3,i%7,2,4).fill({texture,color:0x345678,alpha:.26});c.moveTo(0,0).lineTo(90,30).stroke({texture,width:1.25,color:0xc9e6ee,alpha:.26});return c;}
function build(sys:PIXI.GraphicsContextSystem,c:PIXI.GraphicsContext){const gpu=sys.updateGpuContext(c);const data=sys.getContextRenderData(c);expect(gpu.isBatchable).toBe(false);expect(gpu.geometryData.vertices.length).toBeGreaterThan(400);const batch=data.instructions.instructions[0] as PIXI.Batch;expect(batch instanceof PIXI.Batch).toBe(true);expect(batch.textures.count).toBeGreaterThan(0);return{gpu,data,batch,payload:{vertices:[...gpu.geometryData.vertices],uvs:[...gpu.geometryData.uvs],indices:[...gpu.geometryData.indices],styles:gpu.batches.map(b=>[b.baseColor,b.alpha,b.topology,b.indexOffset,b.indexSize,b.attributeOffset,b.attributeSize])}};}
function returned(batch:PIXI.Batch,sources:PIXI.TextureSource[]){expect(batch.textures.count).toBe(0);expect(sources.every((s,i)=>batch.textures.textures[i]===null&&batch.textures.ids[s.uid]===null)).toBe(true);expect(batch.elements===null&&batch.bindGroup===null&&batch.gpuBindGroup===null&&batch.batcher===null).toBe(true);}
beforeEach(()=>{vi.spyOn(PIXI.DOMAdapter.get(),'createCanvas').mockReturnValue({getContext:()=>null} as unknown as ReturnType<ReturnType<typeof PIXI.DOMAdapter.get>['createCanvas']>);});
afterEach(()=>vi.restoreAllMocks());
it('owned standalone destroy clears returned counted sources while another live batch and shared resources survive',()=>{const sys=host(),texture=new PIXI.Texture({source:new PIXI.TextureSource({width:16,height:16})}),old=draw(texture),live=draw(texture);try{const retired=build(sys,old),current=build(sys,live),batch=retired.batch,sources=batch.textures.textures.slice(0,batch.textures.count),oldBatcher=batch.batcher,liveBatcher=current.batch.batcher,shader=liveBatcher.shader,buffer=liveBatcher.geometry.buffers[0].data;const shaderDestroy=vi.spyOn(shader,'destroy');old.destroy();returned(batch,sources);expect(oldBatcher.geometry===null).toBe(true);expect(current.batch.batcher===liveBatcher&&liveBatcher.shader===shader&&liveBatcher.geometry.buffers[0].data===buffer).toBe(true);expect(current.batch.textures.textures.slice(0,current.batch.textures.count).includes(texture.source)).toBe(true);expect(shaderDestroy).not.toHaveBeenCalled();expect(texture.destroyed||texture.source.destroyed).toBe(false);expect(build(sys,live).payload).toEqual(current.payload);}finally{cleanup(()=>{if(!old.destroyed)old.destroy();},()=>live.destroy(),()=>sys.destroy(),()=>texture.destroy(true));}});
it('actual begin return and reuse restore geometry style counted sources and ids',()=>{const sys=host(),texture=new PIXI.Texture({source:new PIXI.TextureSource({width:16,height:16})}),c=draw(texture);try{const first=build(sys,c),batch=first.batch,sources=batch.textures.textures.slice(0,batch.textures.count),batcher=first.data.batcher;batcher.begin();returned(batch,sources);first.data.instructions.reset();for(const element of first.gpu.batches)batcher.add(element);batcher.finish(first.data.instructions);const next=first.data.instructions.instructions.slice(0,first.data.instructions.instructionSize).find(instruction=>instruction===batch) as PIXI.Batch;expect(next===batch).toBe(true);expect(next.batcher===batcher).toBe(true);expect(next.size).toBeGreaterThan(0);expect(next.textures.count).toBe(sources.length);expect(sources.every((s,i)=>next.textures.textures[i]===s&&next.textures.ids[s.uid]===i)).toBe(true);expect(build(sys,c).payload).toEqual(first.payload);}finally{cleanup(()=>c.destroy(),()=>sys.destroy(),()=>texture.destroy(true));}});
it('clear failure propagates exact first error and failed batch is not available to next checkout',()=>{const sys=host(),texture=new PIXI.Texture({source:new PIXI.TextureSource({width:16,height:16})}),c=draw(texture),next=draw(texture);try{const first=build(sys,c),batch=first.batch,originalBatcher=batch.batcher,sources=batch.textures.textures.slice(0,batch.textures.count),error=Error('counted clear failure');const clear=vi.spyOn(batch.textures,'clear').mockImplementation(()=>{throw error;});let thrown:unknown;try{first.data.batcher.destroy();}catch(e){thrown=e;}expect(thrown===error).toBe(true);expect(clear).toHaveBeenCalledTimes(1);expect(batch.batcher===originalBatcher).toBe(true);expect(batch.textures.textures.slice(0,batch.textures.count)).toEqual(sources);const checked=build(sys,next);expect(checked.batch===batch).toBe(false);expect(checked.payload).toEqual(first.payload);clear.mockRestore();}finally{cleanup(()=>c.destroy(),()=>next.destroy(),()=>sys.destroy(),()=>texture.destroy(true));}});
