import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import * as PIXI from 'pixi.js';
interface DrawBatch {bindGroup?:PIXI.BindGroup|null;gpuBindGroup?:unknown;size:number;}
interface RenderData {batcher:{batches:DrawBatch[];batchIndex:number};instructions:{instructionSize:number};}
let nextUid=12000;
function host(type?:PIXI.RendererType,maxTextures=16){const renderer={uid:++nextUid,type,limits:{maxBatchableTextures:maxTextures},gc:{now:0,addResourceHash:()=>undefined}};const system=new PIXI.GraphicsContextSystem(renderer as unknown as ConstructorParameters<typeof PIXI.GraphicsContextSystem>[0]);return{renderer,system};}
function context(texture:PIXI.Texture){const c=new PIXI.GraphicsContext();c.batchMode='no-batch';for(let i=0;i<120;i++)c.rect(i*3,i%9,2,5).fill({texture,color:0x345678,alpha:.26});return c;}
function data(h:ReturnType<typeof host>,c:PIXI.GraphicsContext){h.system.updateGpuContext(c);return h.system.getContextRenderData(c) as unknown as RenderData;}
function active(d:RenderData){expect(d.batcher.batchIndex).toBeGreaterThan(0);expect(d.instructions.instructionSize).toBeGreaterThan(0);return d.batcher.batches.slice(0,d.batcher.batchIndex);}
function cleanup(...actions:(()=>void)[]){vi.restoreAllMocks();let failed=false,first:unknown;for(const action of actions)try{action();}catch(error){if(!failed){failed=true;first=error;}}if(failed)throw first;}
beforeEach(()=>{vi.spyOn(PIXI.DOMAdapter.get(),'createCanvas').mockReturnValue({getContext:()=>null} as unknown as ReturnType<ReturnType<typeof PIXI.DOMAdapter.get>['createCanvas']>);});
afterEach(()=>vi.restoreAllMocks());
it('real WebGL render data has populated geometry without logical texture groups or added source/style listeners across dirty rebuild',()=>{const h=host(PIXI.RendererType.WEBGL),texture=new PIXI.Texture({source:new PIXI.TextureSource({width:16,height:16})}),c=context(texture),live=context(texture);try{const before=[texture.source.listenerCount('change'),texture.source.style.listenerCount('change')];const gpu=h.system.updateGpuContext(c);const vertices=[...gpu.geometryData.vertices];expect(vertices.length).toBeGreaterThan(400);expect(active(data(h,c)).every(b=>b.bindGroup==null&&b.gpuBindGroup==null)).toBe(true);const liveGpu=h.system.updateGpuContext(live);c.rect(500,20,3,4).fill({texture,color:0x345678,alpha:.26});expect(active(data(h,c)).every(b=>b.bindGroup==null)).toBe(true);expect(h.system.getGpuContext(c).geometryData.vertices.length).toBeGreaterThan(vertices.length);c.destroy();expect(h.system.getGpuContext(live)===liveGpu).toBe(true);expect(texture.destroyed||texture.source.destroyed).toBe(false);expect([texture.source.listenerCount('change'),texture.source.style.listenerCount('change')]).toEqual(before);}finally{cleanup(()=>{if(!c.destroyed)c.destroy();},()=>live.destroy(),()=>h.system.destroy(),()=>texture.destroy(true));}});
it('WEBGPU, CANVAS and unknown backend preserve actual eager groups and borrowed resources',()=>{for(const type of [PIXI.RendererType.WEBGPU,PIXI.RendererType.CANVAS,undefined]){const h=host(type),texture=new PIXI.Texture({source:new PIXI.TextureSource({width:16,height:16})}),c=context(texture);try{const batches=active(data(h,c));expect(batches.every(b=>b.bindGroup instanceof PIXI.BindGroup)).toBe(true);const group=batches[0].bindGroup;if(!group)throw Error('eager group absent');expect(group.getResource(0)===texture.source).toBe(true);expect(group.getResource(1)===texture.source.style).toBe(true);c.destroy();expect(texture.destroyed||texture.source.destroyed).toBe(false);expect(group.getResource(0)===texture.source).toBe(true);}finally{cleanup(()=>{if(!c.destroyed)c.destroy();},()=>h.system.destroy(),()=>texture.destroy(true));}}});
it('ordinary context unload and backend reconfiguration reconstruct correct eager group width while shared survivor remains live',()=>{const h=host(PIXI.RendererType.WEBGL,16),texture=new PIXI.Texture({source:new PIXI.TextureSource({width:16,height:16})}),c=context(texture),live=context(texture);try{expect(active(data(h,c)).every(b=>b.bindGroup==null)).toBe(true);const liveGpu=h.system.updateGpuContext(live);c.unload();h.renderer.type=PIXI.RendererType.WEBGPU;h.renderer.limits.maxBatchableTextures=32;const batches=active(data(h,c));const group=batches[0].bindGroup;if(!group)throw Error('reconfigured GPU group absent');expect(Object.keys(group.resources)).toHaveLength(64);expect(group.getResource(0)===texture.source).toBe(true);expect(h.system.getGpuContext(live)===liveGpu).toBe(true);expect(texture.source.destroyed).toBe(false);}finally{cleanup(()=>c.destroy(),()=>live.destroy(),()=>h.system.destroy(),()=>texture.destroy(true));}});
