import assert from 'node:assert/strict';import test from 'node:test';
import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {deflateSync} from 'node:zlib';
import {capturePublicCDPCanvas,readCanvas,strictBase64,decodeStrictPng,crc32,sha256,baselineHelperSHA256,CAPTURE_MS,MAX_PNG_BYTES} from './public-cdp-capture.mjs';
const root=process.env.ZK682_CANONICAL_SOURCE_ROOT;assert.ok(root,'root must supply exact target app-root');const baselinePath=resolve(root,'scripts/zk682-public-canvas-capture.mjs');assert.equal(sha256(readFileSync(baselinePath)),baselineHelperSHA256);const baseline=await import(pathToFileURL(baselinePath).href);
const state={current:true,connected:true,visible:true,tag:'CANVAS',x:12,y:12,width:100,height:80,viewportWidth:1280,viewportHeight:720,intrinsicWidth:100,intrinsicHeight:80,dpr:1,zoom:1};
const chunk=(type,data)=>{const length=Buffer.alloc(4);length.writeUInt32BE(data.length);const body=Buffer.concat([Buffer.from(type),data]),crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(body));return Buffer.concat([length,body,crc]);};
function png({width=100,height=80,uniform=false,transparent=false}={}){const header=Buffer.alloc(13);header.writeUInt32BE(width,0);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;const raw=Buffer.alloc(height*(1+width*4));for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=y*(1+width*4)+1+x*4;raw[i]=uniform?30:(x<3||y<3||x>=width-3||y>=height-3)?255:0;raw[i+1]=180;raw[i+2]=80;raw[i+3]=transparent?0:255;}return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);}
function fixture(options={}){let count=options.count??1,evaluations=0,detached=0,disposed=0,published=0,sent,sessionCalls=0;const bytes=options.bytes??png();const handle={evaluate:async()=>structuredClone(evaluations++===0?state:options.after??state),dispose:async()=>{disposed++;if(Object.hasOwn(options,'disposeError'))throw options.disposeError;}};const session={send:async(method,args)=>{sent={method,args};if(Object.hasOwn(options,'primary'))throw options.primary;return options.sendPromise??{data:options.data??bytes.toString('base64')};},detach:async()=>{detached++;if(Object.hasOwn(options,'detachError'))throw options.detachError;return options.detachPromise;}};const page={locator:()=>({count:async()=>count}),$:async()=>options.noHandle?null:handle,context:()=>({newCDPSession:()=>{sessionCalls++;return options.sessionPromise??Promise.resolve(session);}})};return {page,handle,session,bytes,publish:()=>{published++;},stats:()=>({detached,disposed,published,sent,sessionCalls}),capture:async extra=>{const result=await capturePublicCDPCanvas(page,{canvasClip:baseline.canvasClip,...extra});published++;return result;}};}
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const clock=()=>{let now=0,fire,cleared=0;return {timing:{now:()=>now,set:(fn,ms)=>{assert.equal(ms,CAPTURE_MS);fire=fn;return 1;},clear:()=>{cleared++;}},expire:()=>{now=CAPTURE_MS;fire();},advance:n=>{now=n;},stats:()=>({now,cleared})};};
const tick=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
test('public CDP sends exact same validated DPR1 clip and cleans before publishing',async()=>{const f=fixture(),result=await f.capture();assert.deepEqual(result.receipt.clip,baseline.canvasClip(state));assert.equal(result.receipt.sha256,sha256(f.bytes));assert.equal(result.receipt.pixelSHA256,decodeStrictPng(f.bytes).pixelSHA256);assert.deepEqual(f.stats().sent,{method:'Page.captureScreenshot',args:{format:'png',clip:{x:12,y:12,width:100,height:80,scale:1},fromSurface:true,captureBeyondViewport:false,optimizeForSpeed:false}});assert.equal(f.stats().detached,1);assert.equal(f.stats().disposed,1);assert.equal(f.stats().published,1);});
test('falsy primary identity wins over secondary detach and handle disposal failures',async()=>{for(const value of [undefined,null,false,0,'']){const f=fixture({primary:value,detachError:new Error('secondary detach'),disposeError:new Error('secondary dispose')});let rejected=false,actual;try{await f.capture();}catch(error){rejected=true;actual=error;}assert.equal(rejected,true);assert.equal(actual,value);assert.deepEqual([f.stats().detached,f.stats().disposed,f.stats().published],[1,1,0]);}});
test('cleanup rejection alone is primary and prevents publication; both cleanup paths run',async()=>{for(const field of ['detachError','disposeError']){const primary=Symbol(field),f=fixture({[field]:primary});await assert.rejects(f.capture(),error=>error===primary);assert.deepEqual([f.stats().detached,f.stats().disposed,f.stats().published],[1,1,0]);}});
test('deadline suppresses late capture result and session is detached once',async()=>{const pending=deferred(),c=clock(),f=fixture({sendPromise:pending.promise});const result=f.capture({timing:c.timing});await tick();assert.equal(f.stats().sessionCalls,1);c.expire();await assert.rejects(result,/deadline10000ms/);pending.resolve({data:f.bytes.toString('base64')});await tick();assert.deepEqual([f.stats().detached,f.stats().disposed,f.stats().published],[1,1,0]);});
test('session acquisition and cleanup consume the same deadline; late acquisition is disposed',async()=>{const pending=deferred(),c=clock(),f=fixture({sessionPromise:pending.promise});const result=f.capture({timing:c.timing});await tick();c.expire();await assert.rejects(result,/deadline10000ms/);pending.resolve(f.session);await tick();assert.deepEqual([f.stats().detached,f.stats().disposed,f.stats().published],[1,1,0]);const detach=deferred(),d=clock(),g=fixture({detachPromise:detach.promise});const final=g.capture({timing:d.timing});await tick();assert.equal(g.stats().detached,1);d.expire();await assert.rejects(final,/deadline10000ms/);detach.resolve();await tick();assert.equal(g.stats().published,0);});
test('unique/current/connected/visible/zero/DPR/geometry guards stop capture and still dispose owned handles',async()=>{for(const count of [0,2]){const f=fixture({count});await assert.rejects(f.capture());assert.equal(f.stats().sessionCalls,0);assert.equal(f.stats().published,0);}for(const mutation of [{current:false},{connected:false},{visible:false},{width:0},{dpr:2},{x:12.1}]){const f=fixture({after:{...state,...mutation}});await assert.rejects(f.capture());assert.deepEqual([f.stats().detached,f.stats().disposed,f.stats().published],[1,1,0]);}const no=fixture({noHandle:true});await assert.rejects(no.capture());assert.equal(no.stats().sessionCalls,0);});
test('strict base64 preallocation, PNG CRC/dimensions/encoding/pixels reject malformed data',async()=>{const bytes=png();assert.deepEqual(strictBase64(bytes.toString('base64')),bytes);for(const data of ['',bytes.toString('base64')+'\n','!!!!','A'.repeat(4*Math.ceil(MAX_PNG_BYTES/3)+4),'AA=A'])assert.throws(()=>strictBase64(data));const corrupt=Buffer.from(bytes);corrupt[corrupt.length-1]^=1;assert.throws(()=>decodeStrictPng(corrupt));assert.throws(()=>decodeStrictPng(bytes,{width:99,height:80}));for(const input of [png({uniform:true}),png({transparent:true}),Buffer.alloc(0),Buffer.alloc(MAX_PNG_BYTES+1)])assert.throws(()=>decodeStrictPng(input));const bad=fixture({data:'!!!!'});await assert.rejects(bad.capture());assert.deepEqual([bad.stats().detached,bad.stats().disposed,bad.stats().published],[1,1,0]);});
test('actual readCanvas rejects duplicate and stale node identity with baseline geometry semantics',()=>{const saved=Object.fromEntries(['document','getComputedStyle','innerWidth','innerHeight','devicePixelRatio','visualViewport'].map(k=>[k,globalThis[k]]));const node={isConnected:true,tagName:'CANVAS',width:100,height:80,getBoundingClientRect:()=>({x:12,y:12,width:100,height:80})};let matches=[node];Object.assign(globalThis,{document:{querySelectorAll:()=>matches},getComputedStyle:()=>({display:'block',visibility:'visible',opacity:'1'}),innerWidth:1280,innerHeight:720,devicePixelRatio:1,visualViewport:{scale:1}});try{assert.deepEqual(readCanvas(node),state);matches=[node,node];assert.throws(()=>baseline.canvasClip(readCanvas(node)));matches=[{...node}];assert.throws(()=>baseline.canvasClip(readCanvas(node)));}finally{for(const [key,value]of Object.entries(saved)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}});
