import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {spawn,execFileSync} from 'node:child_process';import {readFileSync,writeFileSync,mkdirSync,readdirSync,lstatSync,realpathSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {setTimeout as delay} from 'node:timers/promises';
import {capturePublicCDPCanvas,decodeStrictPng,sha256,baselineHelperSHA256} from './public-cdp-capture.mjs';
const target='f822040144de80314f1eb61a7de26f2bac7f3764',app=realpathSync(process.env.ZK682_CANONICAL_SOURCE_ROOT),out=resolve(process.env.C1_OUTPUT_ROOT),driverRoot=realpathSync(process.env.C1_DRIVER_ROOT),started=performance.now(),controlEnd=started+110000;
const ensure=()=>assert.ok(performance.now()<controlEnd,'finite110s inner control deadline');const git=(cwd,...args)=>execFileSync('git',args,{cwd,encoding:'utf8',timeout:5000,maxBuffer:65536}).trim();
assert.equal(git(app,'rev-parse','HEAD'),target);const driver=git(driverRoot,'rev-parse','HEAD');assert.match(driver,/^[0-9a-f]{40}$/);assert.notEqual(driver,target);assert.equal(process.env.C1_DRIVER_SHA,driver);for(const key of ['GITHUB_SHA','VITE_COMMIT_SHA','ZK682_EXPECTED_COMMIT'])assert.equal(process.env[key],target,'target child alias '+key);
const helper=resolve(app,'scripts/zk682-public-canvas-capture.mjs');assert.equal(sha256(readFileSync(helper)),baselineHelperSHA256);const baseline=await import(pathToFileURL(helper).href),require=createRequire(resolve(app,'package.json')),{chromium}=require('@playwright/test');
const allowed=new Set(['identity.json','comparison.json','static-page.png','static-cdp.png','scene-page.png','scene-cdp.png','static-page-receipt.json','static-cdp-receipt.json','scene-page-receipt.json','scene-cdp-receipt.json']);mkdirSync(out,{recursive:true});
const total=()=>{let bytes=0;for(const name of readdirSync(out)){assert.ok(allowed.has(name),'unknown control artifact');const file=resolve(out,name),stat=lstatSync(file);assert.ok(stat.isFile()&&!stat.isSymbolicLink());assert.ok(stat.size<=(name.endsWith('.json')?65536:1048576));bytes+=stat.size;}return bytes;};
const write=(name,data)=>{assert.ok(allowed.has(name));const bytes=Buffer.isBuffer(data)?data:Buffer.from(JSON.stringify(data,null,2)+'\n');assert.ok(bytes.length<=(name.endsWith('.json')?65536:1048576));assert.ok(total()+bytes.length+16384<=1048576,'aggregate artifacts need disposition reserve');writeFileSync(resolve(out,name),bytes,{flag:'wx'});};
write('identity.json',{targetCommit:target,driverCommit:driver,aliases:Object.fromEntries(['GITHUB_SHA','VITE_COMMIT_SHA','ZK682_EXPECTED_COMMIT'].map(k=>[k,process.env[k]])),baselineHelperSHA256,playwrightVersion:require('@playwright/test/package.json').version,qualification:'Actual target dependency/runtime; tmp comparison only, no canonical workload or repair credit'});
let browser,context,server,serverExited=false,timedOut=false;const rows=[],disposition={passed:false,staticPassed:false,sceneAttempted:false,errors:[],qualification:'Both public APIs may share Chromium CDP backend; single initial paused large-scene comparison does not establish cause or canonical reliability. Pixel mismatch is failing without tolerance.'};
const stop=setTimeout(()=>{timedOut=true;context?.close().catch(()=>{});browser?.close().catch(()=>{});server?.kill('SIGTERM');},110000);
async function compare(page,label){ensure();const oldStart=performance.now();let oldReceipt,oldDecoded,oldFailure;
 const baselinePage={locator:page.locator.bind(page),$:page.$.bind(page),screenshot:async options=>{const bytes=await page.screenshot(options);decodeStrictPng(bytes,options.clip);assert.ok(total()+bytes.length+16384<=1048576,'baseline PNG aggregate cap before donor publication');return bytes;}};
 try{oldReceipt=await baseline.captureVisibleCanvas(baselinePage,resolve(out,label+'-page.png'));ensure();const oldBytes=readFileSync(resolve(out,label+'-page.png'));oldDecoded=decodeStrictPng(oldBytes,oldReceipt.clip);assert.equal(oldReceipt.sha256,sha256(oldBytes));write(label+'-page-receipt.json',oldReceipt);rows.push({label,api:'page',passed:true,elapsedMs:performance.now()-oldStart,sha256:sha256(oldBytes),pixelSHA256:oldDecoded.pixelSHA256});}
 catch(error){oldFailure={error};rows.push({label,api:'page',passed:false,elapsedMs:performance.now()-oldStart,error:String(error).slice(0,1024)});}
 const direct=await capturePublicCDPCanvas(page,{canvasClip:baseline.canvasClip});ensure();assert.ok(performance.now()<direct.receipt.deadlineHostMs,'CDP publication inside same10s deadline');write(label+'-cdp.png',direct.png);assert.ok(performance.now()<direct.receipt.deadlineHostMs,'CDP receipt publication inside same10s deadline');write(label+'-cdp-receipt.json',direct.receipt);ensure();const decoded=decodeStrictPng(direct.png,direct.receipt.clip);rows.push({label,api:'cdp',passed:true,elapsedMs:direct.receipt.elapsedMs,sha256:direct.receipt.sha256,pixelSHA256:decoded.pixelSHA256});
 if(oldFailure)throw oldFailure.error;assert.deepEqual(direct.receipt.before,oldReceipt.after,'same current canvas geometry across both APIs');assert.deepEqual(decoded.pixels,oldDecoded.pixels,'exact decoded pixel parity required');return decoded;}

try{
 server=spawn('npm',['run','dev','--','--configLoader','runner','--mode','e2e','--host','127.0.0.1','--port','4174','--strictPort'],{cwd:app,env:process.env,stdio:'ignore'});server.on('error',error=>disposition.errors.push(String(error).slice(0,1024)));server.on('exit',()=>{serverExited=true;});const bootEnd=performance.now()+25000;while(true){ensure();assert.ok(!serverExited,'target dev server exited');try{const response=await fetch('http://127.0.0.1:4174',{signal:AbortSignal.timeout(1000)});if(response.ok)break;}catch{}assert.ok(performance.now()<bootEnd,'target readiness25s exceeded');await delay(200);}
 browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1280,height:720},deviceScaleFactor:1});const page=await context.newPage();page.setDefaultTimeout(20000);page.setDefaultNavigationTimeout(20000);
 await page.setContent('<style>html,body{margin:0;padding:0}</style><div class="cc-pixi-stage"><canvas width="100" height="80" style="display:block;margin:12px;width:100px;height:80px"></canvas></div>');await page.evaluate(()=>{const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');ctx.fillStyle='rgb(255,0,0)';ctx.fillRect(0,0,100,80);ctx.fillStyle='rgb(0,180,80)';ctx.fillRect(3,3,94,74);ctx.fillStyle='rgb(0,0,255)';ctx.fillRect(35,25,30,30);});
 const staticImage=await compare(page,'static');for(let y=0;y<80;y++)for(let x=0;x<100;x++){const expected=x<3||y<3||x>=97||y>=77?[255,0,0,255]:x>=35&&x<65&&y>=25&&y<55?[0,0,255,255]:[0,180,80,255];assert.deepEqual([...staticImage.pixels.subarray((y*100+x)*4,(y*100+x)*4+4)],expected,'static border/center exact actual pixels');}disposition.staticPassed=true;
 // Actual scene is entered only after all static guards and decoded parity pass.
 ensure();await page.addInitScript(()=>localStorage.setItem('coursecraft_app_profile_v5',JSON.stringify({version:5,tutorialOffered:true,tutorialCompleted:true,gameplay:{autosaveCadence:'off'}})));await page.goto('http://127.0.0.1:4174');const quickStart=page.getByRole('button',{name:'Quick Start'});assert.equal(await quickStart.count(),1);await quickStart.click();await page.locator('.cc-pixi-stage canvas').waitFor({state:'visible'});
 await page.waitForFunction(()=>window.__coursecraftPixiTest?.rendererAtlasState().rendered.status==='activated'&&window.__coursecraftTest?.state().screen==='game',null,{timeout:20000});await page.evaluate(()=>document.activeElement?.blur());const speed=await page.evaluate(()=>window.__coursecraftTest.state().speed);if(speed!=='paused')await page.keyboard.press('Space');await page.waitForFunction(()=>window.__coursecraftTest.state().speed==='paused',null,{timeout:10000});
 const observed=await page.evaluate(()=>{const state=JSON.parse(window.render_game_to_text()),renderer=window.__coursecraftPixiTest.rendererAtlasState();return {width:state.course?.width,height:state.course?.height,holeSlots:state.course?.holeSetups?.length,screen:state.screen,speed:state.simulation?.speed,commit:renderer.pathMaterialCrossSection.commit};});assert.deepEqual(observed,{width:220,height:140,holeSlots:9,screen:'game',speed:'paused',commit:target});disposition.scene=observed;disposition.sceneAttempted=true;await compare(page,'scene');disposition.passed=true;
}catch(error){disposition.errors.push(String(error).slice(0,2048));}
finally{clearTimeout(stop);for(const object of [context,browser])if(object)try{await Promise.race([object.close(),delay(1000).then(()=>{throw new Error('browser cleanup1s exceeded');})]);}catch(error){disposition.passed=false;disposition.errors.push(String(error).slice(0,1024));}if(server)server.kill('SIGTERM');disposition.timedOut=timedOut;disposition.elapsedMs=performance.now()-started;disposition.rows=rows;disposition.rootVisualQA='REQUIRED_ACTUAL_PNG_UNSUPPLIED';if(timedOut)disposition.passed=false;try{write('comparison.json',disposition);assert.ok(total()<=1048576);}catch(error){console.error(String(error).slice(0,2048));disposition.passed=false;}console.log(JSON.stringify({passed:disposition.passed,staticPassed:disposition.staticPassed,sceneAttempted:disposition.sceneAttempted,elapsedMs:disposition.elapsedMs}));}
process.exitCode=disposition.passed?0:1;
