import assert from 'node:assert/strict';
import {readFileSync,openSync,readSync,closeSync,existsSync,realpathSync,statSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';import {join} from 'node:path';
import {prepareFixture,runController,publishBoundedReport,firstFailure,failureKind,assertSourceFence} from './observer.mjs';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),admission=JSON.parse(readFileSync(process.argv[2],'utf8'));
assert.equal(admission.unit,'CANVAS_STATE_CONTINUITY_FIRST_DIVERGENT_STAGE');assert.equal(admission.issue,'ZK-1306');assert.equal(admission.sourceAccepted,true);assert.equal(admission.runtimeAdmitted,true);assert.equal(admission.runtimeCap,1);assert.equal(admission.runtimeInvocations,0);assert.equal(admission.prerequisiteBudgetMs,5000);assert.equal(admission.reportByteCap,16384);
assertSourceFence(readFileSync(new URL(import.meta.url),'utf8'));
for(const row of admission.pins){const bytes=readFileSync(row.path);assert.equal(bytes.length,row.bytes);assert.equal(hash(bytes),row.sha256);}
const review=JSON.parse(readFileSync(admission.reviewPath,'utf8'));assert.equal(review.decision,admission.acceptedReviewDecision);assert.ok(String(review.decision).includes('SOURCE_GO')&&!/HOLD|NO_SOURCE_GO/.test(review.decision));
assert.equal(admission.fixtureSHA256,'ae2f4678d7f68d30c0087a75438e4019b22f8756391f689179f51da9b36be93a');assert.equal(hash(Buffer.from(admission.fixtureHTML)),admission.fixtureSHA256);
const prepared=prepareFixture(admission.fixtureHTML);assert.equal(hash(Buffer.from(prepared.html)),admission.observedFixtureSHA256);
const binary=admission.binary;assert.equal(realpathSync(binary.path),binary.realpath);assert.equal(statSync(binary.path).size,binary.bytes);const descriptor=openSync(binary.path,'r'),chunk=Buffer.alloc(1048576),digest=createHash('sha256');try{let length;while((length=readSync(descriptor,chunk,0,chunk.length,null))>0)digest.update(chunk.subarray(0,length));}finally{closeSync(descriptor);}assert.equal(digest.digest('hex'),binary.sha256);assert.equal(JSON.parse(readFileSync(admission.sdkPackage,'utf8')).version,'1.61.1');
if(process.argv.includes('--preflight-only')){console.log(JSON.stringify({preflightPassed:true,browserLaunches:0,runtimeInvocations:0}));process.exit(0);}
const output=admission.output;assert.equal(existsSync(output),true);for(const name of ['runtime-intent.json','result.json'])assert.equal(existsSync(join(output,name)),false);writeFileSync(join(output,'runtime-intent.json'),JSON.stringify({unit:admission.unit,issue:'ZK-1306',runtimeInvocation:1,admissionSHA256:hash(readFileSync(process.argv[2]))})+'\n',{flag:'wx'});
const started=performance.now(),failure={failed:false,primary:undefined},closure=[];let browser,context,page,observed;
try{const {chromium}=await import(pathToFileURL(admission.sdkEntry).href);browser=await chromium.launch({headless:true,timeout:30000});assert.equal(browser.version(),binary.version);context=await browser.newContext({viewport:{width:160,height:120},deviceScaleFactor:1,isMobile:false,hasTouch:false});page=await context.newPage();observed=await runController(page,prepared.html);if(observed.failure.failed&&!failure.failed)Object.assign(failure,observed.failure);}catch(error){firstFailure(failure,error);}finally{for(const [name,resource]of [['page',page],['context',context],['browser',browser]])if(resource)try{await resource.close();closure.push({name,closed:true});}catch(error){closure.push({name,closed:false,failureKind:failureKind(error)});firstFailure(failure,error);}}
const result={unit:admission.unit,issue:'ZK-1306',outcome:failure.failed||!observed?.trace.valid||!observed?.trace.complete?'STATE_TRACE_FAIL_OR_INCOMPLETE':'STATE_TRACE_OBSERVED_PENDING_OWNER_CLOSURE',firstFailurePresent:failure.failed,firstFailureKind:failure.failed?(failure.firstKind??failureKind(failure.primary)):null,trace:observed?.trace??{valid:false,reason:'NO_TRACE'},events:observed?.events??{valid:false,pageerrorState:'UNKNOWN',consoleState:'UNKNOWN'},closure,elapsedMs:performance.now()-started,runtimeInvocation:1,helperImports:0,helperInvocations:0,CDPSessions:0,screenshots:0,releaseCleared:false,qualification:'State continuity observer/readbacks perturb fixture. First divergent stage is observed mismatch, not writer/backend cause. Context loss false/no events and mutation delivery do not exclude every reset. No capture, performance, canonical or release credit.'};
const publication=publishBoundedReport({writeFileSync},join(output,'result.json'),result,failure);console.log(JSON.stringify({outcome:publication.record.outcome,written:publication.written,firstFailurePresent:failure.failed,firstFailureKind:failure.failed?(failure.firstKind??failureKind(failure.primary)):null,closure}));if(failure.failed||!publication.written||!observed?.trace.valid||!observed?.trace.complete)process.exitCode=1;
