import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {CANDIDATE,WORKFLOW,BRANCH,PINS,SDK_PINS,ARTIFACT_PATHS,sha,validateRoles,artifactName,verifyArtifactName,verifyCheckouts,validateMetadata,selectHeadless,launchEvidence,classifyTrace,validateClosure,boundedWrite,validateArtifacts,verifySource} from './host.mjs';
const here=dirname(fileURLToPath(import.meta.url)),packet=process.env.ZK1307_SOURCE_PACKET_ROOT||resolve(here,'../../..');
const roles=()=>({source_sha:'a'.repeat(40),candidate_sha:CANDIDATE,github_sha:'a'.repeat(40),run_id:'123456',run_attempt:'1',workflow_path:WORKFLOW,branch:BRANCH});
function temporary(fn){const p=fs.mkdtempSync(join(tmpdir(),'zk1307-host-control-'));try{return fn(p);}finally{fs.rmSync(p,{recursive:true,force:true});}}
function metadata(){return {platform:'linux',nodeMajor:22,arch:'x64',kernel:'6.8.0',imageOS:'ubuntu24',imageVersion:'20261001.1',osRelease:'ID=ubuntu',sdkVersion:'1.61.1',coreVersion:'1.61.1',revision:'1228',expectedVersion:'149.0.7827.55',...Object.fromEntries([['sdkPackage','package'],['sdkEntry','entry'],['coreBundle','core']].map(([key,p])=>[key,{path:'/controlled/'+key,bytes:SDK_PINS[p][0],sha256:SDK_PINS[p][1]}])),binary:{path:'/controlled/chrome-headless-shell',bytes:123,sha256:'b'.repeat(64)}};}
const names=['S0_INLINE_POSTDRAW','S1_POSTLOAD','S2_FIRST_RAF','S3_SECOND_RAF'];
function trace(){return {firstFailurePresent:false,trace:{valid:true,complete:true,overflow:false,malformed:false,frozen:true,getImageDataCalls:4,frameCallbacks:2,stages:names.map((stage,i)=>({stage,ordinal:i+1,uniqueCurrent:true,sameNode:true,connected:true,intrinsicWidth:32,intrinsicHeight:16,width:32,height:16,dpr:1,imageRead:true,pixelMismatchCount:0,channelMismatchCount:0,fillStyle:'#00ff00',isContextLost:false,samples:[[0,0,0,255,0,255],[3,3,0,255,0,255],[4,0,255,0,0,255],[15,15,255,0,0,255],[16,0,0,0,255,255],[31,15,0,0,255,255]]}))}};}
test('exact roles and artifact bind source separately from unchanged candidate',()=>{const r=roles();assert.equal(validateRoles(r).source_sha,r.source_sha);verifyArtifactName(r,artifactName(r));for(const [key,value]of [['source_sha','bad'],['source_sha',CANDIDATE],['github_sha','b'.repeat(40)],['candidate_sha','b'.repeat(40)],['run_id','0'],['run_id','9007199254740993'],['run_attempt','0'],['run_attempt','2'],['workflow_path','other.yml'],['branch','main']])assert.throws(()=>validateRoles({...r,[key]:value}));for(const wrong of [artifactName({...r,source_sha:CANDIDATE}),artifactName({...r,run_id:'999'}),artifactName({...r,run_attempt:'2'})])assert.throws(()=>verifyArtifactName(r,wrong));});
test('real separate Git checkouts reject swapped identities aliases and dirty source',()=>temporary(p=>{function git(root,...args){return execFileSync('git',['-C',root,...args],{encoding:'utf8',timeout:10000,maxBuffer:65536}).trim();}function repo(name){const root=join(p,name);fs.mkdirSync(root);git(root,'init','--quiet');git(root,'config','user.email','controlled@example.invalid');git(root,'config','user.name','Controlled');fs.writeFileSync(join(root,'file'),name);git(root,'add','file');git(root,'commit','--quiet','-m','fixture');return root;}const s=repo('source'),c=repo('candidate'),r={source_sha:git(s,'rev-parse','HEAD'),candidate_sha:git(c,'rev-parse','HEAD')};verifyCheckouts(s,c,r);assert.throws(()=>verifyCheckouts(s,s,r));assert.throws(()=>verifyCheckouts(c,s,r));assert.throws(()=>verifyCheckouts(s,c,{...r,source_sha:'a'.repeat(40)}));fs.writeFileSync(join(s,'unexpected'),'dirty');assert.throws(()=>verifyCheckouts(s,c,r));}));
test('immutable observer controller review supervisor and exact fixture provenance',()=>{for(const [name,[size,hash]]of Object.entries(PINS)){const b=fs.readFileSync(join(here,name));assert.equal(b.length,size);assert.equal(sha(b),hash);}const f=JSON.parse(fs.readFileSync(join(here,'fixture.json')));assert.equal(sha(Buffer.from(f.fixtureHTML)),f.fixtureSHA256);assert.equal(f.fixtureSHA256,'ae2f4678d7f68d30c0087a75438e4019b22f8756391f689179f51da9b36be93a');assert.equal(f.observedFixtureSHA256,'6441d483355d31a082b9fce4c8f2f90ee83606f5861ca7b83864ae45a4b5eea5');const review=JSON.parse(fs.readFileSync(join(here,'source-review.json')));assert.equal(review.decision,'SOURCE_GO_QUALIFIED_ZK1306_STATE_CONTINUITY_OBSERVER');const controller=fs.readFileSync(join(here,'control.mjs'),'utf8');assert.ok(controller.includes('chromium.launch({headless:true,timeout:30000})'));assert.ok(!controller.includes('executablePath:'));});
test('metadata rejects SDK core platform Node revision version and missing image facts',()=>{assert.equal(validateMetadata(metadata()).revision,'1228');for(const [key,value]of [['platform','darwin'],['nodeMajor',26],['arch','unknown'],['sdkVersion','1.61.0'],['coreVersion','1.61.0'],['revision','1243'],['expectedVersion','150.0'],['kernel',''],['imageOS',undefined],['imageVersion',undefined],['osRelease','']])assert.throws(()=>validateMetadata({...metadata(),[key]:value}));const m=metadata();m.coreBundle.sha256='0'.repeat(64);assert.throws(()=>validateMetadata(m));const n=metadata();delete n.binary;assert.throws(()=>validateMetadata(n));});
test('default headless shell discovery rejects wrong revision missing alias and unsupported bindings',()=>temporary(p=>{const f=binaryFixture(p),options=binaryOptions();const selected=selectHeadless(f.publicPath,options);assert.equal(selected.path,f.binary);assert.equal(selected.provenance.identityChecksAfterPinning,false);selected.verify();assert.equal(selected.provenance.identityChecksAfterPinning,true);assert.throws(()=>selectHeadless(f.publicPath.replace('1228','1243'),options));for(const change of [{platform:'darwin'},{arch:'unknown'},{registry:undefined},{registry:binaryRegistry().map(x=>({...x,revision:'1243'}))},{registry:binaryRegistry().map(x=>({...x,revisionOverrides:{'ubuntu24.04-x64':'1243'}}))}])assert.throws(()=>selectHeadless(f.publicPath,{...options,...change}));fs.unlinkSync(f.binary);assert.throws(()=>selectHeadless(f.publicPath,options));}));
test('actual DEBUG launch evidence must match bound binary and exactly one launch',()=>{const line='2026-10-09T00:00:00.000Z pw:browser <launching> /controlled/chrome-headless-shell --headless --no-sandbox';assert.equal(launchEvidence(line,'/controlled/chrome-headless-shell').observed,true);assert.throws(()=>launchEvidence(line,'/other/chrome'));assert.throws(()=>launchEvidence(line+'\n'+line,'/controlled/chrome-headless-shell'));assert.throws(()=>launchEvidence('no launch','/controlled/chrome-headless-shell'));assert.throws(()=>launchEvidence('x'.repeat(262145),'/controlled/chrome-headless-shell'));});
test('outcomes are neutral for persistent state local-like loss other divergence and incomplete',()=>{const healthy=trace();assert.equal(classifyTrace(healthy),'AUTHORED_STATE_PERSISTS_FOUR_STAGES');const lost=trace();for(const s of lost.trace.stages.slice(1)){s.pixelMismatchCount=512;s.channelMismatchCount=1024;s.fillStyle='#000000';s.isContextLost=true;s.samples=s.samples.map(v=>[v[0],v[1],0,0,0,0]);}assert.equal(classifyTrace(lost),'LOCAL_LIKE_CONTEXTLOSS_AFTER_INLINE_DRAW');assert.equal(lost.trace.contextEvents,undefined);const other=trace();other.trace.stages[2].pixelMismatchCount=1;assert.equal(classifyTrace(other),'OTHER_OBSERVED_STATE_CONTINUITY');const initial=trace();initial.trace.stages[0].pixelMismatchCount=1;assert.equal(classifyTrace(initial),'INITIAL_DRAW_NOT_ESTABLISHED');for(const mutate of [x=>x.trace.stages.pop(),x=>x.trace.frameCallbacks=1,x=>x.trace.getImageDataCalls=3,x=>x.firstFailurePresent=true,x=>x.trace.stages[0].stage='S1_POSTLOAD',x=>x.trace.stages[1].sameNode=false,x=>x.trace.overflow=true]){const x=trace();mutate(x);assert.equal(classifyTrace(x),'INCOMPLETE_OR_FAILED_TRACE');}});
test('owned receipt must prove 120/180 completion with no live or zombie descendants',()=>{const good={exitCode:0,cause:null,closureVerified:true,childReaped:true,finalReconciliationCompleted:true,ownershipObservationFailed:false,ownedStillObserved:[],ownedLiveStillObserved:[],ownedZombieStillObserved:[],passed:true,workerSeconds:120,parentSeconds:180};validateClosure(good);for(const [key,value]of [['exitCode',1],['cause','WORKER_DEADLINE'],['closureVerified',false],['childReaped',false],['finalReconciliationCompleted',false],['ownershipObservationFailed',true],['ownedLiveStillObserved',[123]],['ownedZombieStillObserved',[123]],['workerSeconds',600],['parentSeconds',660]])assert.throws(()=>validateClosure({...good,[key]:value}));});
test('exclusive bounded JSON and exact artifact path caps preserve sentinel and reject aliases',()=>temporary(p=>{const sentinel=join(p,'sentinel');fs.writeFileSync(sentinel,'original');assert.throws(()=>boundedWrite(sentinel,{changed:true}));assert.equal(fs.readFileSync(sentinel,'utf8'),'original');assert.throws(()=>boundedWrite(join(p,'oversize'),{v:'x'.repeat(65536)}));assert.equal(fs.existsSync(join(p,'oversize')),false);for(const name of ARTIFACT_PATHS){const path=join(p,name);fs.mkdirSync(dirname(path),{recursive:true});fs.writeFileSync(path,name.endsWith('.log')?'':'{}');}assert.equal(validateArtifacts(p).length,5);fs.writeFileSync(join(p,'owner/stdout.log'),'a'.repeat(131073));fs.writeFileSync(join(p,'owner/stderr.log'),'a'.repeat(131072));assert.throws(()=>validateArtifacts(p));fs.writeFileSync(join(p,'owner/stdout.log'),'');fs.writeFileSync(join(p,'owner/stderr.log'),'');fs.unlinkSync(join(p,'trace/result.json'));fs.symlinkSync(sentinel,join(p,'trace/result.json'));assert.throws(()=>validateArtifacts(p));}));
test('single-job workflow routes exact roles and finite five paths with full baseline inverse',()=>{const w=fs.readFileSync(join(packet,WORKFLOW),'utf8'),inverse=JSON.parse(fs.readFileSync(join(packet,'workflow-inverse.json')));assert.equal(sha(Buffer.from(w)),inverse.generated.sha256);assert.equal(Buffer.byteLength(w),inverse.generated.bytes);const restored=Buffer.from(inverse.originalBase64,'base64');assert.equal(restored.length,11356);assert.equal(sha(restored),'ebf2d12c9944d833315a3bc2058f567f6c937a69f8f6702a4185627476aebb47');assert.match(w,/jobs:\n  state-continuity:\n/);assert.equal((w.match(/    runs-on:/g)||[]).length,1);assert.ok(!/linux-evidence:|native-evidence:|aggregate:|npm run build|renderer-proof|certification-contract/.test(w));for(const literal of ['node-version: \'22\'','timeout-minutes: 10','path: source','path: candidate','ref: ${{ inputs.source_sha }}','ref: ${{ inputs.candidate_sha }}','--verify-only','--run','install --with-deps chromium','if: always()','if-no-files-found: error'])assert.ok(w.includes(literal),literal);const paths=w.split('          path: |\n')[1].trim().split('\n').map(x=>x.trim().replace(/^zk1307-output\//,''));assert.deepEqual(paths,ARTIFACT_PATHS);assert.ok(!w.includes('executablePath'));assert.ok(!w.includes('channel:'));});
test('host source fences intent before SDK import and supervisor before neutral classification',()=>{const h=fs.readFileSync(join(here,'host.mjs'),'utf8');assert.ok(h.indexOf("boundedWrite(join(output,'host-intent.json')")<h.indexOf('await import(pathToFileURL(sdkEntry).href)'));assert.ok(h.indexOf("validateClosure(receipt)")<h.indexOf('context.disposition=classifyTrace(trace)'));assert.ok(h.includes("'--seconds','120','--artifact-cap','8388608'"));assert.ok(h.includes('timeout:180000'));assert.ok(h.includes("env:{...env,DEBUG:'pw:browser'}"));assert.ok(!/chromium\.launch|\.newPage\(|\.screenshot\(|\.newCDPSession\(/.test(h));function fence(source){assert.ok(source.includes('beforeSDKImport:true'));assert.ok(source.indexOf("boundedWrite(join(output,'host-intent.json')")>=0);assert.ok(source.indexOf("boundedWrite(join(output,'host-intent.json')")<source.indexOf('await import(pathToFileURL(sdkEntry).href)'));assert.ok(!/chromium\.launch|\.newPage\(|\.screenshot\(|\.newCDPSession\(/.test(source));}fence(h);for(const changed of [h.replace('beforeSDKImport:true','beforeSDKImport:false'),h.replace("boundedWrite(join(output,'host-intent.json')","boundedWrite(join(output,'wrong-intent.json')"),h+'\nchromium.launch({channel:"chrome"});'])assert.throws(()=>fence(changed));});
test('actual source preparation rejects old lock and external source-module owner before probe',()=>temporary(p=>{const baseline=process.env.ZK1307_BASELINE_ROOT;assert.ok(baseline,'ROOT supplies pinned baseline root');function git(root,...args){return execFileSync('git',['-C',root,...args],{encoding:'utf8',timeout:10000,maxBuffer:65536}).trim();}const source=join(p,'source'),candidate=join(p,'candidate'),moduleRoot=join(source,'simgolf-lite/scripts/zk1307-state-continuity');fs.mkdirSync(moduleRoot,{recursive:true});fs.mkdirSync(join(source,'.github/workflows'),{recursive:true});fs.copyFileSync(join(packet,WORKFLOW),join(source,WORKFLOW));for(const name of ['host.mjs','host.test.mjs','fixture.json',...Object.keys(PINS)])fs.copyFileSync(join(here,name),join(moduleRoot,name));fs.mkdirSync(join(candidate,'simgolf-lite'),{recursive:true});for(const name of ['package.json','package-lock.json'])fs.copyFileSync(join(baseline,'simgolf-lite',name),join(candidate,'simgolf-lite',name));for(const root of [source,candidate]){git(root,'init','--quiet');git(root,'config','user.email','controlled@example.invalid');git(root,'config','user.name','Controlled');git(root,'add','.');git(root,'commit','--quiet','-m','controlled fixture');}let r={source_sha:git(source,'rev-parse','HEAD'),candidate_sha:git(candidate,'rev-parse','HEAD')};assert.equal(verifySource(source,candidate,r,moduleRoot).lockPin.sha256,'0866f32e72d93d3eb2112f4b3a07f3f6366429c8575a47ef12a6083f7506e391');assert.throws(()=>verifySource(source,candidate,r,here));const lock=join(candidate,'simgolf-lite/package-lock.json');fs.appendFileSync(lock,' ');git(candidate,'add','.');git(candidate,'commit','--quiet','-m','wrong lock');r.candidate_sha=git(candidate,'rev-parse','HEAD');assert.throws(()=>verifySource(source,candidate,r,moduleRoot));}));

import {readOSRelease,pin as currentPin} from './host.mjs';
function osFixture(root,alias=false,content='ID=ubuntu\nVERSION_ID=24.04\n'){
 fs.mkdirSync(join(root,'etc'),{recursive:true});fs.mkdirSync(join(root,'usr/lib'),{recursive:true});
 const target=join(root,alias?'usr/lib/os-release':'etc/os-release');fs.writeFileSync(target,content);
 if(alias)fs.symlinkSync('../usr/lib/os-release',join(root,'etc/os-release'));
 const base=fs.realpathSync(root),mapped=logical=>join(base,logical.slice(1)),audit={opened:0,closed:0,flags:null,readCalls:0};
 const io={constants:fs.constants,lstatSync:q=>fs.lstatSync(mapped(q)),readlinkSync:q=>fs.readlinkSync(mapped(q)),realpathSync:q=>{const actual=fs.realpathSync(mapped(q));assert.ok(actual===base||actual.startsWith(base+'/'));return actual===base?'/':actual.slice(base.length);},openSync:(q,flags)=>{audit.opened++;audit.flags=flags;return fs.openSync(mapped(q),flags);},fstatSync:fd=>fs.fstatSync(fd),readSync:(...args)=>{audit.readCalls++;return fs.readSync(...args);},closeSync:fd=>{audit.closed++;return fs.closeSync(fd);}};
 return {io,audit,mapped,target,content};
}
test('os-release correction: direct and canonical alias exact bytes and provenance',()=>{for(const alias of [false,true])temporary(p=>{const f=osFixture(p,alias),r=readOSRelease(f.io);assert.equal(r.text,f.content);assert.equal(r.provenance.requestedPath,'/etc/os-release');assert.equal(r.provenance.resolvedPath,alias?'/usr/lib/os-release':'/etc/os-release');assert.equal(r.provenance.requestedType,alias?'symlink':'regular');assert.equal(r.provenance.targetType,'regular');assert.equal(r.provenance.bytes,Buffer.byteLength(f.content));assert.equal(r.provenance.sha256,sha(Buffer.from(f.content)));assert.ok(Object.values(r.provenance.identityChecks).every(Boolean));assert.equal(f.audit.opened,1);assert.equal(f.audit.closed,1);assert.ok((f.audit.flags&fs.constants.O_NOFOLLOW)!==0);assert.ok(f.audit.readCalls<=2);});});
test('os-release correction: foreign broken chained directory empty and oversized refuse',()=>{for(const kind of ['foreign','broken','chain','directory','empty','oversize','requested-directory'])temporary(p=>{const f=osFixture(p,true),link=f.mapped('/etc/os-release'),target=f.mapped('/usr/lib/os-release');if(kind==='foreign'){fs.unlinkSync(link);fs.symlinkSync('../foreign/os-release',link);}if(kind==='broken')fs.unlinkSync(target);if(kind==='chain'){fs.renameSync(target,join(p,'usr/lib/other'));fs.symlinkSync('other',target);}if(kind==='directory'){fs.unlinkSync(target);fs.mkdirSync(target);}if(kind==='empty')fs.writeFileSync(target,'');if(kind==='oversize')fs.writeFileSync(target,'x'.repeat(32769));if(kind==='requested-directory'){fs.unlinkSync(link);fs.mkdirSync(link);}assert.throws(()=>readOSRelease(f.io),kind);assert.equal(f.audit.opened,0);assert.equal(f.audit.closed,0);});temporary(p=>{const f=osFixture(p,false,'x'.repeat(32768));assert.equal(readOSRelease(f.io).provenance.bytes,32768);});});
test('os-release correction: requested and target replacements during read reject and close',()=>{for(const kind of ['requested','target','before-open','growth','short-read'])temporary(p=>{const f=osFixture(p,true),read=f.io.readSync,open=f.io.openSync;let changed=false;if(kind==='before-open')f.io.openSync=(q,flags)=>{fs.renameSync(f.target,f.target+'.retained');fs.writeFileSync(f.target,f.content);return open(q,flags);};else f.io.readSync=(...args)=>{if(kind==='short-read')return 0;const n=read(...args);if(!changed){changed=true;if(kind==='requested'){const link=f.mapped('/etc/os-release');fs.unlinkSync(link);fs.symlinkSync('/usr/lib/os-release',link);}if(kind==='target'){fs.unlinkSync(f.target);fs.writeFileSync(f.target,f.content);}if(kind==='growth')fs.appendFileSync(f.target,'changed');}return n;};assert.throws(()=>readOSRelease(f.io),kind);assert.equal(f.audit.opened,1);assert.equal(f.audit.closed,1);});});
test('os-release correction: canonical parent alias and identity races refuse',()=>{temporary(p=>{const f=osFixture(p,true),lib=join(p,'usr/lib');fs.renameSync(lib,join(p,'usr/real-lib'));fs.symlinkSync('real-lib',lib);assert.throws(()=>readOSRelease(f.io));assert.equal(f.audit.opened,0);});temporary(p=>{const f=osFixture(p,true),read=f.io.readSync;let changed=false;f.io.readSync=(...args)=>{const n=read(...args);if(!changed){changed=true;const dir=join(p,'etc');fs.renameSync(dir,join(p,'etc-old'));fs.mkdirSync(dir);fs.symlinkSync('../usr/lib/os-release',join(dir,'os-release'));}return n;};assert.throws(()=>readOSRelease(f.io));assert.equal(f.audit.closed,1);});temporary(p=>{const f=osFixture(p,true),original=f.io.lstatSync;f.io.lstatSync=q=>{const s=original(q);if(q==='/usr'&&f.audit.readCalls>0)return Object.assign(Object.create(s),{ino:s.ino+1});return s;};assert.throws(()=>readOSRelease(f.io));assert.equal(f.audit.closed,1);});});
test('os-release correction: first falsy read failure survives close failure',()=>temporary(p=>{const f=osFixture(p,true),close=f.io.closeSync;f.io.readSync=()=>{throw false;};f.io.closeSync=fd=>{close(fd);throw new Error('secondary close');};let caught=false,value;try{readOSRelease(f.io);}catch(error){caught=true;value=error;}assert.equal(caught,true);assert.equal(value,false);assert.equal(f.audit.closed,1);temporary(q=>{const g=osFixture(q,true);g.io.constants={...fs.constants,O_NOFOLLOW:undefined};assert.throws(()=>readOSRelease(g.io));assert.equal(g.audit.opened,0);});}));
test('os-release correction: source1 counterfactual alias fails while generic pin still refuses symlinks',()=>temporary(p=>{const f=osFixture(p,true);assert.ok(readOSRelease(f.io).text.includes('ID=ubuntu'));const old=fs.readFileSync(join(process.env.ZK1307_SOURCE1_ROOT,'simgolf-lite/scripts/zk1307-state-continuity/host.mjs'),'utf8');const body=old.match(/function read\(path,cap\)\{[^\n]+\}/)?.[0];assert.ok(body);const oldRead=new Function('assert','lstatSync','readFileSync',body+'; return read;')(assert,f.io.lstatSync,q=>fs.readFileSync(f.mapped(q)));assert.throws(()=>oldRead('/etc/os-release',32768));const bytes=fs.readFileSync(f.target);assert.equal(sha(bytes),sha(Buffer.from(f.content)));assert.throws(()=>currentPin(f.mapped('/etc/os-release'),32768));}));

function binaryRegistry(){return ['chromium','chromium-headless-shell'].map(name=>({name,revision:'1228',browserVersion:'149.0.7827.55'}));}
function binaryOptions(arch='x64'){return {platform:'linux',arch,registry:binaryRegistry()};}
function binaryFixture(p,arch='x64'){const root=fs.realpathSync(p),chromium=join(root,'chromium-1228','chrome-linux64'),shell=join(root,'chromium_headless_shell-1228'),architecture=join(shell,arch==='x64'?'chrome-headless-shell-linux64':'chrome-linux');fs.mkdirSync(chromium,{recursive:true});fs.mkdirSync(architecture,{recursive:true});const publicPath=join(chromium,'chrome'),binary=join(architecture,arch==='x64'?'chrome-headless-shell':'headless_shell');fs.writeFileSync(publicPath,'controlled full chromium');fs.writeFileSync(binary,'controlled shell');fs.chmodSync(binary,0o644);return {root,publicPath,shell,architecture,binary};}
test('binary selection correction: exact x64 ignores unrelated entries and source2 walk fails cap',()=>temporary(p=>{const f=binaryFixture(p);for(let i=0;i<140;i++)fs.writeFileSync(join(f.shell,'unrelated-'+String(i).padStart(3,'0')),'x');const options=binaryOptions();options.io={lstatSync:fs.lstatSync,realpathSync:fs.realpathSync,readdirSync(){throw new Error('enumeration forbidden');}};const selected=selectHeadless(f.publicPath,options);assert.equal(selected.path,f.binary);selected.verify();const old=fs.readFileSync(join(process.env.ZK1307_SOURCE2_ROOT,'simgolf-lite/scripts/zk1307-state-continuity/host.mjs'),'utf8');const body=old.match(/export function selectHeadless\(publicPath\)\{[^\n]+\}/)?.[0];assert.ok(body);const previous=new Function('assert','dirname','basename','join','lstatSync','readdirSync',body.replace('export ','')+';return selectHeadless;')(assert,dirname,x=>x.split('/').at(-1),join,fs.lstatSync,fs.readdirSync);assert.throws(()=>previous(f.publicPath));assert.ok(selected.provenance.selection.includes('no enumeration'));}));
test('binary selection correction: pinned ARM64 suffix and exact finite target refusal',()=>{temporary(p=>{const f=binaryFixture(p,'arm64'),r=selectHeadless(f.publicPath,binaryOptions('arm64'));assert.equal(r.path,f.binary);assert.deepEqual(r.provenance.suffix,['chrome-linux','headless_shell']);r.verify();});for(const kind of ['cache-alias','shell-link','architecture-link','final-link','directory','zero','oversize','canonical-spelling'])temporary(p=>{const f=binaryFixture(p);let publicPath=f.publicPath,options=binaryOptions();if(kind==='cache-alias'){const alias=f.root+'-alias';fs.symlinkSync(f.root,alias);try{assert.throws(()=>selectHeadless(join(alias,'chromium-1228','chrome-linux64','chrome'),options));}finally{fs.unlinkSync(alias);}return;}if(kind==='shell-link'){fs.renameSync(f.shell,f.shell+'-real');fs.symlinkSync(f.shell+'-real',f.shell);}if(kind==='architecture-link'){fs.renameSync(f.architecture,f.architecture+'-real');fs.symlinkSync(f.architecture+'-real',f.architecture);}if(kind==='final-link'){fs.renameSync(f.binary,f.binary+'-real');fs.symlinkSync(f.binary+'-real',f.binary);}if(kind==='directory'){fs.unlinkSync(f.binary);fs.mkdirSync(f.binary);}if(kind==='zero')fs.writeFileSync(f.binary,'');if(kind==='oversize')fs.truncateSync(f.binary,536870913);if(kind==='canonical-spelling')publicPath=f.publicPath.replace('/chromium-1228/','/chromium-1228/../chromium-1228/');assert.throws(()=>selectHeadless(publicPath,options),kind);});});
test('binary selection correction: stable target and parents checked after unchanged stream pin',()=>{for(const kind of ['target-replacement','target-size','target-mode','parent-replacement'])temporary(p=>{const f=binaryFixture(p),selected=selectHeadless(f.publicPath,binaryOptions());const binaryPin=currentStreamPin(f.binary);assert.equal(binaryPin.bytes,Buffer.byteLength('controlled shell'));assert.equal(binaryPin.sha256,sha(Buffer.from('controlled shell')));if(kind==='target-replacement'){fs.renameSync(f.binary,f.binary+'-old');fs.writeFileSync(f.binary,'controlled shell');}if(kind==='target-size')fs.appendFileSync(f.binary,'changed');if(kind==='target-mode')fs.chmodSync(f.binary,0o600);if(kind==='parent-replacement'){fs.renameSync(f.architecture,f.architecture+'-old');fs.mkdirSync(f.architecture);fs.renameSync(join(f.architecture+'-old','chrome-headless-shell'),f.binary);}assert.throws(()=>selected.verify(),kind);assert.equal(selected.provenance.identityChecksAfterPinning,false);});});

import {streamPin as currentStreamPin} from './host.mjs';
