import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,lstatSync,realpathSync,readdirSync,openSync,readSync,closeSync,existsSync,readlinkSync,fstatSync,constants} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync,spawnSync} from 'node:child_process';
import {resolve,join,dirname,basename} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import os from 'node:os';
export const CANDIDATE='f0a12b98792f4719b8f2c3a8c23a093171be428c';
export const WORKFLOW='.github/workflows/zk682-certification.yml';
export const BRANCH='codex/zk1307-canvas-state-continuity';
export const ARTIFACT_PATHS=['trace/result.json','source-context.json','owner/owned-command-receipt.json','owner/stdout.log','owner/stderr.log'];
export const PINS={
 'observer.mjs':[16855,'3a711d734dcd81b3361ae8002d8721ad28119750525d7c04e6072d0ff9be5af2'],
 'control.mjs':[4927,'0bcf6e2296f4e63c6901afba198ad57ba55bd00ba0d080f6309238eb90664fa4'],
 'source-review.json':[3744,'4c0ad0c6ba9f9e2d4049b16f5ca70b2bfc073dda9229dd6571f515c315d0c967'],
 'owned-supervisor.py':[13112,'c5754c194c90aedbd893543264f9ee7b36f832d95a92cdc49c5e42cfb2fa4007']};
export const SDK_PINS={package:[1559,'6b840268612656f0639fb7d68782e8353bdf11518589d30ddf66f283c2670ed5'],entry:[704,'a0f5715ea22354f922791a9c53dc012d5d5c067ff9cc4cd35ffb7cd272071a9f'],core:[3352341,'6be5c2ea035554e9b184b1dbc7aa5e7f1fb428dd1b5c202022858dcfae9bee27']};
export const sha=b=>createHash('sha256').update(b).digest('hex');
function read(path,cap){const s=lstatSync(path);assert.ok(s.isFile()&&!s.isSymbolicLink()&&s.size<=cap,'regular bounded file');const b=readFileSync(path);assert.equal(b.length,s.size);return b;}
export function pin(path,cap=8388608){const b=read(path,cap);return {path:resolve(path),bytes:b.length,sha256:sha(b)};}
function match(path,expected,cap=8388608){const p=pin(path,cap);assert.equal(p.bytes,expected[0]);assert.equal(p.sha256,expected[1]);return p;}
const OS_RELEASE_IO={lstatSync,realpathSync,readlinkSync,openSync,fstatSync,readSync,closeSync,constants};
export function readOSRelease(io=OS_RELEASE_IO){
 const requestedPath='/etc/os-release',cap=32768,requestedBefore=io.lstatSync(requestedPath);
 const identity=s=>({dev:s.dev,ino:s.ino,mode:s.mode,size:s.size,mtimeMs:s.mtimeMs,ctimeMs:s.ctimeMs});
 const requestedType=requestedBefore.isSymbolicLink()?'symlink':requestedBefore.isFile()?'regular':'other';
 assert.ok(requestedType==='regular'||requestedType==='symlink','OS release requested type');
 let resolvedPath=requestedPath,linkText=null;
 if(requestedType==='symlink'){linkText=io.readlinkSync(requestedPath);assert.ok(linkText==='../usr/lib/os-release'||linkText==='/usr/lib/os-release','canonical OS release alias');resolvedPath='/usr/lib/os-release';}
 const parentPaths=resolvedPath===requestedPath?['/','/etc']:['/','/etc','/usr','/usr/lib'];
 const parentIdentity=path=>{const s=io.lstatSync(path);assert.ok(s.isDirectory()&&!s.isSymbolicLink(),'OS release canonical parent');assert.equal(io.realpathSync(path),path,'OS release parent alias');return {path,dev:s.dev,ino:s.ino,mode:s.mode};};
 const parentsBefore=parentPaths.map(parentIdentity);
 assert.equal(io.realpathSync(requestedPath),resolvedPath,'OS release target allowlist');
 const targetBefore=io.lstatSync(resolvedPath);assert.ok(targetBefore.isFile()&&!targetBefore.isSymbolicLink(),'OS release regular target');
 assert.ok(Number.isSafeInteger(targetBefore.size)&&targetBefore.size>0&&targetBefore.size<=cap,'OS release nonempty bounded target');
 assert.ok(Number.isInteger(io.constants.O_NOFOLLOW)&&io.constants.O_NOFOLLOW>0,'OS release nofollow available');
 let fd,bytes,failed=false,primary;
 try{
  fd=io.openSync(resolvedPath,io.constants.O_RDONLY|io.constants.O_NOFOLLOW|(io.constants.O_NONBLOCK||0));
  const opened=io.fstatSync(fd);assert.ok(opened.isFile(),'OS release descriptor type');assert.deepEqual(identity(opened),identity(targetBefore),'OS release descriptor identity');
  const buffer=Buffer.alloc(cap+1);let length=0;
  while(length<buffer.length){const n=io.readSync(fd,buffer,length,buffer.length-length,null);assert.ok(Number.isInteger(n)&&n>=0&&n<=buffer.length-length,'OS release read length');if(n===0)break;length+=n;}
  assert.ok(length>0&&length<=cap,'OS release bounded bytes');assert.equal(length,targetBefore.size,'OS release stable length');bytes=buffer.subarray(0,length);
  assert.deepEqual(identity(io.fstatSync(fd)),identity(targetBefore),'OS release descriptor stable after read');
  assert.deepEqual(identity(io.lstatSync(resolvedPath)),identity(targetBefore),'OS release target stable after read');
  assert.deepEqual(identity(io.lstatSync(requestedPath)),identity(requestedBefore),'OS release requested stable after read');
  if(requestedType==='symlink')assert.equal(io.readlinkSync(requestedPath),linkText,'OS release link stable after read');
  assert.equal(io.realpathSync(requestedPath),resolvedPath,'OS release resolution stable after read');
  assert.deepEqual(parentPaths.map(parentIdentity),parentsBefore,'OS release parents stable after read');
 }catch(error){failed=true;primary=error;}finally{if(fd!==undefined)try{io.closeSync(fd);}catch(error){if(!failed){failed=true;primary=error;}}}
 if(failed)throw primary;
 const text=bytes.toString('utf8');assert.ok(text.length>0,'OS release nonempty string');
 return {text,provenance:{requestedPath,resolvedPath,requestedType,targetType:'regular',linkText,bytes:bytes.length,sha256:sha(bytes),requestedIdentity:identity(requestedBefore),targetIdentity:identity(targetBefore),parents:parentsBefore,identityChecks:{requested:true,target:true,descriptor:true,parents:true,resolution:true,linkText:true},nofollow:true,qualification:'Bounded stable path/descriptor observations only; does not identify the prior failed hosted path or exclude later changes.'}};
}
export function validateRoles(r){assert.match(r.source_sha,/^[0-9a-f]{40}$/);assert.equal(r.candidate_sha,CANDIDATE);assert.notEqual(r.source_sha,r.candidate_sha);assert.equal(r.github_sha,r.source_sha);assert.match(r.run_id,/^[1-9][0-9]*$/);assert.ok(Number.isSafeInteger(Number(r.run_id))&&Number(r.run_id)>0);assert.equal(r.run_attempt,'1');assert.equal(r.workflow_path,WORKFLOW);assert.equal(r.branch,BRANCH);return {source_sha:r.source_sha,candidate_sha:r.candidate_sha,run_id:r.run_id,run_attempt:r.run_attempt,workflow_path:r.workflow_path};}
export function artifactName(r){return `zk1307-state-continuity-${r.source_sha}-${r.run_id}-${r.run_attempt}`;}
export function verifyArtifactName(r,name){assert.equal(name,artifactName(r));}
function git(root,...args){return execFileSync('git',['-C',root,...args],{encoding:'utf8',timeout:10000,maxBuffer:65536}).trim();}
export function verifyCheckouts(source,candidate,r){assert.notEqual(realpathSync(source),realpathSync(candidate));assert.equal(git(source,'rev-parse','HEAD'),r.source_sha);assert.equal(git(candidate,'rev-parse','HEAD'),r.candidate_sha);assert.equal(git(source,'status','--porcelain','--untracked-files=all'),'');assert.equal(git(candidate,'status','--porcelain','--untracked-files=all'),'');}
export function validateMetadata(m){assert.equal(m.platform,'linux');assert.equal(m.nodeMajor,22);assert.ok(['x64','arm64'].includes(m.arch));for(const k of ['kernel','imageOS','imageVersion','osRelease'])assert.ok(typeof m[k]==='string'&&m[k].length>0&&m[k].length<=32768,k);assert.equal(m.sdkVersion,'1.61.1');assert.equal(m.coreVersion,'1.61.1');assert.equal(m.revision,'1228');assert.equal(m.expectedVersion,'149.0.7827.55');for(const k of ['sdkPackage','sdkEntry','coreBundle','binary']){const p=m[k];assert.ok(p&&typeof p.path==='string'&&p.path.length>0);assert.ok(Number.isSafeInteger(p.bytes)&&p.bytes>0);assert.match(p.sha256,/^[0-9a-f]{64}$/);}for(const [k,expected]of [['sdkPackage',SDK_PINS.package],['sdkEntry',SDK_PINS.entry],['coreBundle',SDK_PINS.core]]){assert.equal(m[k].bytes,expected[0]);assert.equal(m[k].sha256,expected[1]);}return m;}
export function selectHeadless(publicPath,{platform=process.platform,arch=process.arch,registry,io={lstatSync,realpathSync}}={}){
 assert.equal(platform,'linux','default shell Linux platform');assert.ok(Array.isArray(registry),'actual browser registry entries required');for(const name of ['chromium','chromium-headless-shell']){const entries=registry.filter(x=>x.name===name);assert.equal(entries.length,1,'unique pinned registry browser');assert.equal(String(entries[0].revision),'1228','pinned registry revision');assert.equal(entries[0].browserVersion,'149.0.7827.55','pinned registry browser version');assert.equal(Object.hasOwn(entries[0],'revisionOverrides'),false,'unsupported revision overrides');}const suffix=arch==='x64'?['chrome-headless-shell-linux64','chrome-headless-shell']:arch==='arm64'?['chrome-linux','headless_shell']:null;assert.ok(suffix,'default shell supported Linux architecture');assert.equal(publicPath,resolve(publicPath),'canonical public executable spelling');
 let root=dirname(publicPath),publicParents=[root];for(let i=0;i<5&&!/^chromium-1228$/.test(basename(root));i++){root=dirname(root);publicParents.push(root);}assert.equal(basename(root),'chromium-1228','public Chromium revision binding');
 const cache=dirname(root),shell=join(cache,'chromium_headless_shell-1228'),architecture=join(shell,suffix[0]),path=join(architecture,suffix[1]);
 const directoryPaths=[...new Set([...publicParents,cache,shell,architecture])];
 const fact=(p,directory)=>{const s=io.lstatSync(p);assert.ok(!s.isSymbolicLink(),'default shell nonsymlink component');assert.ok(directory?s.isDirectory():s.isFile(),'default shell component type');assert.equal(io.realpathSync(p),p,'default shell canonical component');const r={path:p,type:directory?'directory':'regular',dev:s.dev,ino:s.ino,mode:s.mode};if(!directory){assert.ok(Number.isSafeInteger(s.size)&&s.size>0&&s.size<=536870912,'default shell positive bounded binary');Object.assign(r,{bytes:s.size,mtimeMs:s.mtimeMs,ctimeMs:s.ctimeMs});}return r;};
 const before=[...directoryPaths.map(p=>fact(p,true)),fact(path,false)];
 const provenance={platform,arch,revision:'1228',suffix,path,realpath:path,registryPolicy:{revision:'1228',browserVersion:'149.0.7827.55',revisionOverrides:'ABSENT_REQUIRED'},selection:'Exact pinned SDK1.61.1 Linux registry suffix; no enumeration or executable override.',components:before,identityChecksBefore:true,identityChecksAfterPinning:false,defaultUse:'UNKNOWN_UNTIL_ACTUAL_DEBUG_LAUNCH_AGREEMENT'};
 return {path,provenance,verify(){assert.deepEqual([...directoryPaths.map(p=>fact(p,true)),fact(path,false)],before,'default shell stable components after pinning');provenance.identityChecksAfterPinning=true;}};
}
export function streamPin(path){const s=lstatSync(path);assert.ok(s.isFile()&&!s.isSymbolicLink()&&s.size>0&&s.size<=536870912);const fd=openSync(path,'r'),h=createHash('sha256'),b=Buffer.alloc(1048576);let total=0;try{let n;while((n=readSync(fd,b,0,b.length,null))>0){total+=n;assert.ok(total<=536870912);h.update(b.subarray(0,n));}}finally{closeSync(fd);}assert.equal(total,s.size);return {path:resolve(path),realpath:realpathSync(path),bytes:total,sha256:h.digest('hex')};}
export function launchEvidence(log,binaryPath){assert.ok(Buffer.byteLength(log)<=262144);const lines=log.split('\n').filter(x=>x.includes('pw:browser')&&x.includes('<launching>'));assert.equal(lines.length,1,'exactly one recorded default browser launch');assert.ok(Buffer.byteLength(lines[0])<=16384);assert.ok(lines[0].includes(`<launching> ${binaryPath} `),'actual default headless path');return {observed:true,launchLine:lines[0],source:'DEBUG=pw:browser bounded stderr',defaultLaunchOptions:{headless:true,timeout:30000},qualification:'Actual launch line records installed default flags; no backend/flags/executable/channel override supplied.'};}
const STAGES=['S0_INLINE_POSTDRAW','S1_POSTLOAD','S2_FIRST_RAF','S3_SECOND_RAF'];
export function classifyTrace(record){const t=record?.trace;if(record?.firstFailurePresent!==false||!t||t.valid!==true||t.complete!==true||t.overflow!==false||t.malformed!==false||t.frozen!==true||t.getImageDataCalls!==4||t.frameCallbacks!==2||!Array.isArray(t.stages)||t.stages.length!==4)return 'INCOMPLETE_OR_FAILED_TRACE';for(let i=0;i<4;i++){const s=t.stages[i];if(s.stage!==STAGES[i]||s.ordinal!==i+1||s.uniqueCurrent!==true||s.sameNode!==true||s.connected!==true||s.intrinsicWidth!==32||s.intrinsicHeight!==16||s.width!==32||s.height!==16||s.dpr!==1||s.imageRead!==true||!Number.isInteger(s.pixelMismatchCount)||s.pixelMismatchCount<0||s.pixelMismatchCount>512||!Number.isInteger(s.channelMismatchCount)||s.channelMismatchCount<0||s.channelMismatchCount>2048||typeof s.fillStyle!=='string')return 'INCOMPLETE_OR_FAILED_TRACE';}const s=t.stages;if(s[0].pixelMismatchCount!==0||s[0].channelMismatchCount!==0||s[0].fillStyle!=='#00ff00'||s[0].isContextLost!==false)return 'INITIAL_DRAW_NOT_ESTABLISHED';if(s.every(x=>x.pixelMismatchCount===0&&x.channelMismatchCount===0&&x.fillStyle==='#00ff00'&&x.isContextLost===false))return 'AUTHORED_STATE_PERSISTS_FOUR_STAGES';if(s.slice(1).every(x=>x.pixelMismatchCount===512&&x.channelMismatchCount===1024&&x.fillStyle==='#000000'&&x.isContextLost===true&&Array.isArray(x.samples)&&x.samples.length===6&&x.samples.every(v=>Array.isArray(v)&&v.length===6&&v.slice(2).every(n=>n===0))))return 'LOCAL_LIKE_CONTEXTLOSS_AFTER_INLINE_DRAW';return 'OTHER_OBSERVED_STATE_CONTINUITY';}
export function validateClosure(r){assert.equal(r.exitCode,0);assert.equal(r.cause,null);assert.equal(r.closureVerified,true);assert.equal(r.childReaped,true);assert.equal(r.finalReconciliationCompleted,true);assert.equal(r.ownershipObservationFailed,false);for(const k of ['ownedStillObserved','ownedLiveStillObserved','ownedZombieStillObserved'])assert.deepEqual(r[k],[]);assert.equal(r.passed,true);assert.equal(r.workerSeconds,120);assert.equal(r.parentSeconds,180);}
export function boundedWrite(path,value,cap=65536){const b=Buffer.from(JSON.stringify(value,null,2)+'\n');assert.ok(b.length<=cap);writeFileSync(path,b,{flag:'wx'});}
export function validateArtifacts(root){const pins=ARTIFACT_PATHS.map(name=>pin(join(root,name),name==='trace/result.json'?16384:name.endsWith('.log')?262144:65536));assert.ok(pins[3].bytes+pins[4].bytes<=262144);return pins;}
export function verifySource(source,candidate,r,moduleRoot){assert.equal(realpathSync(moduleRoot),realpathSync(join(source,'simgolf-lite/scripts/zk1307-state-continuity')),'source module ownership');verifyCheckouts(source,candidate,r);const local=Object.entries(PINS).map(([name,p])=>match(join(moduleRoot,name),p,65536));const sourcePins=[...local,...['host.mjs','host.test.mjs','fixture.json'].map(name=>pin(join(moduleRoot,name),65536)),pin(join(source,WORKFLOW),65536)];const packagePin=match(join(candidate,'simgolf-lite/package.json'),[11046,'fb50a3ac5421a40fdedd3e89da7d37869c077d1ec99628af2e5a0eeb0e21adf1']);const lockPin=match(join(candidate,'simgolf-lite/package-lock.json'),[328272,'0866f32e72d93d3eb2112f4b3a07f3f6366429c8575a47ef12a6083f7506e391']);const fixture=JSON.parse(read(join(moduleRoot,'fixture.json'),16384));assert.equal(sha(Buffer.from(fixture.fixtureHTML)),'ae2f4678d7f68d30c0087a75438e4019b22f8756391f689179f51da9b36be93a');assert.equal(fixture.fixtureSHA256,'ae2f4678d7f68d30c0087a75438e4019b22f8756391f689179f51da9b36be93a');assert.equal(fixture.observedFixtureSHA256,'6441d483355d31a082b9fce4c8f2f90ee83606f5861ca7b83864ae45a4b5eea5');const review=JSON.parse(read(join(moduleRoot,'source-review.json'),65536));assert.equal(review.decision,'SOURCE_GO_QUALIFIED_ZK1306_STATE_CONTINUITY_OBSERVER');return {local,sourcePins,packagePin,lockPin,fixture,review};}
export async function main(args=process.argv.slice(2),env=process.env){assert.equal(args.length,4);const [sourceArg,candidateArg,outputArg,mode]=args,source=resolve(sourceArg),candidate=resolve(candidateArg),output=resolve(outputArg),moduleRoot=dirname(fileURLToPath(import.meta.url));assert.ok(['--verify-only','--run'].includes(mode));const roles=validateRoles({source_sha:env.SOURCE_SHA,candidate_sha:env.CANDIDATE_SHA,github_sha:env.GITHUB_SHA,run_id:env.GITHUB_RUN_ID,run_attempt:env.GITHUB_RUN_ATTEMPT,workflow_path:env.WORKFLOW_PATH,branch:env.GITHUB_REF_NAME});const checked=verifySource(source,candidate,roles,moduleRoot);if(mode==='--verify-only'){console.log(JSON.stringify({preflightPassed:true,SDKImports:0,browserLaunches:0,...roles}));return;}
assert.equal(env.GITHUB_ACTIONS,'true');assert.equal(existsSync(output),false);mkdirSync(output,{recursive:false});mkdirSync(join(output,'trace'));const context={schemaVersion:1,issue:'ZK-1307',unit:'EQUIVALENT_HOSTED_CANVAS_STATE_CONTINUITY_COMPARISON',...roles,run_id:Number(roles.run_id),run_attempt:1,job_name:'state-continuity',artifact_name:artifactName(roles),artifact_paths:ARTIFACT_PATHS,sourceRoot:source,candidateRoot:candidate,sourcePins:checked.sourcePins,package:checked.packagePin,lock:checked.lockPin,source_review_decision:checked.review.decision,runtimeInvocation:1,runtimeCap:1,retries:0,releaseCleared:false,canonicalCredit:false,disposition:'INCOMPLETE_OR_FAILED_TRACE',backendOwner:'UNKNOWN',cause:'UNKNOWN'};
boundedWrite(join(output,'host-intent.json'),{...roles,unit:context.unit,runtimeInvocation:1,admittedBy:'exact manual workflow source/candidate roles; exclusive workspace intent',beforeSDKImport:true});let failed=false,primary,closureAccepted=false;try{const nodeModules=join(candidate,'simgolf-lite/node_modules'),sdkPackage=join(nodeModules,'playwright/package.json'),sdkEntry=join(nodeModules,'playwright/index.mjs'),corePackage=join(nodeModules,'playwright-core/package.json'),coreBundle=join(nodeModules,'playwright-core/lib/coreBundle.js'),registry=JSON.parse(read(join(nodeModules,'playwright-core/browsers.json'),65536));const browser=registry.browsers.filter(x=>x.name==='chromium-headless-shell');assert.equal(browser.length,1);const osReleaseRead=readOSRelease();const metadata={platform:process.platform,arch:process.arch,nodeMajor:Number(process.versions.node.split('.')[0]),nodeVersion:process.version,kernel:os.release(),imageOS:env.ImageOS,imageVersion:env.ImageVersion,osRelease:osReleaseRead.text,osReleaseProvenance:osReleaseRead.provenance,sdkVersion:JSON.parse(read(sdkPackage,65536)).version,coreVersion:JSON.parse(read(corePackage,65536)).version,revision:String(browser[0].revision),expectedVersion:browser[0].browserVersion,sdkPackage:match(sdkPackage,SDK_PINS.package),sdkEntry:match(sdkEntry,SDK_PINS.entry),coreBundle:streamPin(coreBundle),registry:pin(join(nodeModules,'playwright-core/browsers.json'),65536),corePackage:pin(corePackage,65536)};assert.equal(metadata.platform,'linux');assert.equal(metadata.nodeMajor,22);assert.equal(metadata.sdkVersion,'1.61.1');assert.equal(metadata.coreVersion,'1.61.1');assert.equal(metadata.revision,'1228');assert.equal(metadata.expectedVersion,'149.0.7827.55');assert.equal(metadata.coreBundle.sha256,SDK_PINS.core[1]);context.platform=metadata;const {chromium}=await import(pathToFileURL(sdkEntry).href);const publicPath=chromium.executablePath();metadata.publicChromiumExecutablePath=publicPath;metadata.publicChromiumBinary=streamPin(publicPath);const selectedShell=selectHeadless(publicPath,{registry:registry.browsers});metadata.headlessSelection=selectedShell.provenance;metadata.binary={...streamPin(selectedShell.path),version:metadata.expectedVersion};selectedShell.verify();metadata.defaultPathQualification='Public executablePath names full Chromium. Exact pinned SDK Linux revision-1228 shell suffix is selected without enumeration and bound before default launch; actual DEBUG launch line must agree after launch. No executable override.';validateMetadata(metadata);
const inner={unit:'CANVAS_STATE_CONTINUITY_FIRST_DIVERGENT_STAGE',issue:'ZK-1306',sourceAccepted:true,runtimeAdmitted:true,runtimeCap:1,runtimeInvocations:0,retries:0,prerequisiteBudgetMs:5000,reportByteCap:16384,pins:[...checked.local,pin(join(moduleRoot,'fixture.json'),16384),metadata.sdkPackage,metadata.sdkEntry,metadata.coreBundle],reviewPath:join(moduleRoot,'source-review.json'),acceptedReviewDecision:checked.review.decision,...checked.fixture,binary:metadata.binary,sdkPackage,sdkEntry,output:join(output,'trace'),candidateBase:CANDIDATE,canonicalCredit:false,releaseCleared:false};boundedWrite(join(output,'admission.json'),inner);context.admission=pin(join(output,'admission.json'),65536);context.intent=pin(join(output,'host-intent.json'),65536);const command=['--out',join(output,'owner'),'--seconds','120','--artifact-cap','8388608','--',process.execPath,join(moduleRoot,'control.mjs'),join(output,'admission.json')];context.ownerCommand=command;const result=spawnSync('python3',[join(moduleRoot,'owned-supervisor.py'),...command],{env:{...env,DEBUG:'pw:browser'},encoding:'utf8',maxBuffer:65536,timeout:180000});context.supervisorExitCode=result.status;context.supervisorSignal=result.signal;assert.equal(result.error,undefined);assert.equal(result.status,0);const receipt=JSON.parse(read(join(output,'owner/owned-command-receipt.json'),65536));validateClosure(receipt);closureAccepted=true;metadata.actualBrowserVersion='149.0.7827.55';metadata.browserVersionEvidence='Unchanged controller public browser.version() equality guard passed before complete trace and exit0; registry expectation is separately bound.';const trace=JSON.parse(read(join(output,'trace/result.json'),16384));metadata.defaultLaunch=launchEvidence(read(join(output,'owner/stderr.log'),262144).toString(),metadata.binary.path);metadata.headlessSelection.defaultUse='OBSERVED_DEBUG_LAUNCH_PATH_AGREEMENT';context.disposition=classifyTrace(trace);assert.notEqual(context.disposition,'INCOMPLETE_OR_FAILED_TRACE');context.ownerReceipt=pin(join(output,'owner/owned-command-receipt.json'),65536);context.trace=pin(join(output,'trace/result.json'),16384);assert.ok(pin(join(output,'owner/stdout.log'),262144).bytes+pin(join(output,'owner/stderr.log'),262144).bytes<=262144);context.observedTraceEngineIssue='ZK-1306';context.qualification='Equivalent observer fixture on hosted Linux; state outcomes are neutral. Observer/readbacks perturb fixture. Healthy or recurring loss does not identify OS/component/backend cause or confer capture/performance/release credit.';
}catch(error){failed=true;primary=error;context.failed=true;context.firstFailureKind=error===null?'null':typeof error;context.failureMessage=error instanceof Error?String(error.message).slice(0,2048):'non-Error primary';}finally{context.runtimeClosed=closureAccepted?true:'UNKNOWN';context.runtimeClosureQualification='Owner receipt supplies actual child/descendant closure only when accepted. Missing receipt or outer timeout gives UNKNOWN closure; no universal cleanup claim.';try{boundedWrite(join(output,'source-context.json'),context);}catch(error){if(!failed){failed=true;primary=error;}}}if(failed)throw primary;validateArtifacts(output);console.log(JSON.stringify({issue:'ZK-1307',...roles,artifact:context.artifact_name,disposition:context.disposition,releaseCleared:false}));}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(error=>{console.error(error);process.exitCode=1;});
