export function installCanvasStateObserver(c,g){
 const labels=['S0_INLINE_POSTDRAW','S1_POSTLOAD','S2_FIRST_RAF','S3_SECOND_RAF'],stages=[],contextEvents=[],dimensions=[];
 let done=false,running=false,active='PRE_DRAW',timer,observer,resolveResult,failed=false,primaryKind=null,overflow=false,malformed=false,cleanupFailures=0,reads=0;
 const promise=new Promise(resolve=>{resolveResult=resolve;});
 const kind=error=>error===null?'null':typeof error;
 const fail=error=>{if(!failed){failed=true;primaryKind=kind(error);}};
 const stamp=()=>{const n=performance.now();if(!Number.isFinite(n)||n<0)throw new Error('Invalid page clock');return n;};
 const native=fn=>{try{return typeof fn==='function'?/\{\s*\[native code\]\s*\}/.test(Function.prototype.toString.call(fn)):'UNKNOWN';}catch{return 'UNKNOWN';}};
 const descriptor=(object,key)=>{for(let depth=0;object&&depth<8;depth++,object=Object.getPrototypeOf(object)){const d=Object.getOwnPropertyDescriptor(object,key);if(d)return d;}return undefined;};
 const functionData=(object,key)=>{const d=descriptor(object,key);return d&&Object.hasOwn(d,'value')&&typeof d.value==='function'?d.value:null;};
 const stateValue=key=>{const own=Object.getOwnPropertyDescriptor(g,key);if(own&&!Object.hasOwn(own,'value'))return 'UNKNOWN';let value;if(own)value=own.value;else{const d=Object.getOwnPropertyDescriptor(CanvasRenderingContext2D.prototype,key);if(!d||native(d.get)!==true)return 'UNKNOWN';value=d.get.call(g);}return key==='globalAlpha'?(Number.isFinite(value)&&value>=0&&value<=1?value:'UNKNOWN'):(typeof value==='string'&&new TextEncoder().encode(value).length<=64?value:'UNKNOWN');};
 const safeNumber=n=>typeof n==='number'&&Number.isFinite(n)&&Math.abs(n)<=1e12?n:null;
 const boundedEvent=(list,row)=>{if(done)return;if(list.length>=16||new TextEncoder().encode(JSON.stringify(row)).length>512||new TextEncoder().encode(JSON.stringify({contextEvents:list===contextEvents?[...contextEvents,row]:contextEvents,dimensions:list===dimensions?[...dimensions,row]:dimensions})).length>8192){overflow=true;fail(new Error('Event cap'));finish('OVERFLOW');return;}list.push(row);};
 const lost=()=>{if(done)return;try{boundedEvent(contextEvents,{kind:'contextlost',stage:active,atPageMs:stamp()});}catch(error){malformed=true;fail(error);finish('MALFORMED');}};
 const restored=()=>{if(done)return;try{boundedEvent(contextEvents,{kind:'contextrestored',stage:active,atPageMs:stamp()});}catch(error){malformed=true;fail(error);finish('MALFORMED');}};
 const finish=reason=>{
  if(done)return;done=true;
  for(const [name,fn]of [['contextlost',lost],['contextrestored',restored]])try{c.removeEventListener(name,fn);}catch(error){cleanupFailures++;fail(error);}
  try{observer?.disconnect();}catch(error){cleanupFailures++;fail(error);}try{clearTimeout(timer);}catch(error){cleanupFailures++;fail(error);}
  const mismatch=stages.find(stage=>stage.pixelMismatchCount!==null&&stage.pixelMismatchCount>0),initial=stages[0],stateChange=stages.slice(1).find(stage=>initial&&['fillStyle','globalAlpha','compositeOperation'].some(key=>initial[key]!=='UNKNOWN'&&stage[key]!=='UNKNOWN'&&stage[key]!==initial[key])),complete=stages.length===4&&reads===4&&stages.every(stage=>stage.imageRead&&stage.pixelMismatchCount!==null&&stage.reason!=='SNAPSHOT_ERROR');
  resolveResult({schemaVersion:1,valid:!failed&&!overflow&&!malformed,complete,overflow,malformed,frozen:true,reason,firstFailurePresent:failed,firstFailureKind:primaryKind,cleanupFailures,getImageDataCalls:reads,frameCallbacks:Math.max(0,stages.length-2),stages,contextEvents,dimensions,firstDivergentStage:mismatch?mismatch.stage:'NONE_OBSERVED',firstStateChangeStage:stateChange?stateChange.stage:'NONE_OBSERVED',contextLossCause:'UNKNOWN',compositor:'UNKNOWN',lateDeliveryKnowledge:'UNKNOWN',dimensionWriter:'UNKNOWN'});
 };
 const snapshot=stage=>{
  if(done)return false;active=stage;
  if(stage!==labels[stages.length]||stages.length>=4){malformed=true;fail(new Error('Stage order'));finish('STAGE_ORDER_INVALID');return false;}
  const row={ordinal:stages.length+1,stage,atPageMs:null,uniqueCurrent:false,sameNode:false,connected:false,intrinsicWidth:null,intrinsicHeight:null,x:null,y:null,width:null,height:null,xNegativeZero:false,dpr:null,fillStyle:'UNKNOWN',globalAlpha:'UNKNOWN',compositeOperation:'UNKNOWN',isContextLost:'UNKNOWN',isContextLostNativeAppearance:'UNKNOWN',imageRead:false,pixelMismatchCount:null,channelMismatchCount:null,samples:[[0,0,null,null,null,null],[3,3,null,null,null,null],[4,0,null,null,null,null],[15,15,null,null,null,null],[16,0,null,null,null,null],[31,15,null,null,null,null]],reason:'PENDING'};stages.push(row);
  try{
   row.atPageMs=stamp();const matches=document.querySelectorAll('.cc-pixi-stage canvas');row.uniqueCurrent=matches.length===1;row.sameNode=row.uniqueCurrent&&matches[0]===c;row.connected=c instanceof HTMLCanvasElement&&c.ownerDocument===document&&c.isConnected===true;
   if(!row.sameNode||!row.connected){row.reason='SAME_NODE_GUARD_FAIL';finish('SAME_NODE_GUARD_FAIL');return false;}
   const rectMethod=functionData(c,'getBoundingClientRect');if(!rectMethod)throw new Error('Rect accessor');const rect=rectMethod.call(c);row.intrinsicWidth=safeNumber(c.width);row.intrinsicHeight=safeNumber(c.height);row.x=safeNumber(rect.x);row.y=safeNumber(rect.y);row.width=safeNumber(rect.width);row.height=safeNumber(rect.height);row.xNegativeZero=Object.is(rect.x,-0);row.dpr=safeNumber(devicePixelRatio);
   if(c.width!==32||c.height!==16||rect.x!==0||rect.y!==0||rect.width!==32||rect.height!==16||devicePixelRatio!==1){row.reason='GEOMETRY_GUARD_FAIL';finish('GEOMETRY_GUARD_FAIL');return false;}
   if(typeof CanvasRenderingContext2D!=='function'||!(g instanceof CanvasRenderingContext2D))throw new Error('Context type');row.fillStyle=stateValue('fillStyle');row.globalAlpha=stateValue('globalAlpha');row.compositeOperation=stateValue('globalCompositeOperation');
   const contextLost=functionData(g,'isContextLost');row.isContextLostNativeAppearance=native(contextLost);if(contextLost&&row.isContextLostNativeAppearance===true){const value=contextLost.call(g);row.isContextLost=typeof value==='boolean'?value:'UNKNOWN';}
   const read=functionData(g,'getImageData');if(!read)throw new Error('Image accessor');if(reads>=4)throw new Error('Image cap');reads++;const image=read.call(g,0,0,32,16),pixels=image.data;row.imageRead=true;
   if(image.width!==32||image.height!==16||!(pixels instanceof Uint8ClampedArray)||pixels.length!==2048)throw new Error('Image shape');let pm=0,cm=0;
   for(let y=0;y<16;y++)for(let x=0;x<32;x++){const expected=y<4&&x<4?[0,255,0,255]:x<16?[255,0,0,255]:[0,0,255,255],offset=(y*32+x)*4;let mismatch=false;for(let channel=0;channel<4;channel++)if(pixels[offset+channel]!==expected[channel]){cm++;mismatch=true;}if(mismatch)pm++;}
   row.pixelMismatchCount=pm;row.channelMismatchCount=cm;for(const sample of row.samples){const offset=(sample[1]*32+sample[0])*4;for(let channel=0;channel<4;channel++)sample[channel+2]=pixels[offset+channel];}row.reason=pm?'PIXELS_MISMATCH':'PIXELS_MATCH';return true;
  }catch(error){row.reason='SNAPSHOT_ERROR';malformed=true;fail(error);finish('SNAPSHOT_ERROR');return false;}
 };
 const run=()=>{if(done)return promise;if(running){malformed=true;fail(new Error('Run twice'));finish('RUN_TWICE');return promise;}running=true;if(!snapshot(labels[1]))return promise;if(typeof requestAnimationFrame!=='function'){fail(new Error('RAF absent'));finish('RAF_UNAVAILABLE');return promise;}try{requestAnimationFrame(()=>{if(done)return;if(!snapshot(labels[2]))return;try{requestAnimationFrame(()=>{if(done)return;snapshot(labels[3]);finish('FOUR_STAGES_RECORDED');});}catch(error){fail(error);finish('RAF_REQUEST_ERROR');}});}catch(error){fail(error);finish('RAF_REQUEST_ERROR');}return promise;};
 try{
  c.addEventListener('contextlost',lost);c.addEventListener('contextrestored',restored);
  observer=new MutationObserver(records=>{if(done)return;try{for(const record of records){if(!['width','height'].includes(record.attributeName)||!(record.oldValue===null||typeof record.oldValue==='string'&&new TextEncoder().encode(record.oldValue).length<=64))throw new Error('Mutation shape');const value=record.attributeName==='width'?c.width:c.height;if(!Number.isInteger(value)||value<0||value>1e9)throw new Error('Mutation value');boundedEvent(dimensions,{attribute:record.attributeName,oldValue:record.oldValue,currentValue:value,stage:active,deliveredAtPageMs:stamp()});}}catch(error){malformed=true;fail(error);finish('MALFORMED');}});observer.observe(c,{attributes:true,attributeOldValue:true,attributeFilter:['width','height']});timer=setTimeout(()=>{fail(new Error('Scheduled5000ms'));finish('SCHEDULED_TIMEOUT');},5000);
 }catch(error){fail(error);finish('OBSERVER_SETUP_ERROR');}
 const controller=Object.freeze(Object.defineProperties(Object.create(null),{snapshot:{value:snapshot},run:{value:run}}));
 if(Object.getOwnPropertyDescriptor(globalThis,'__zk1306CanvasObserver'))throw new Error('Observer namespace exists');Object.defineProperty(globalThis,'__zk1306CanvasObserver',{value:controller,writable:false,configurable:false});return controller;
}

export function consumeCanvasObserver(){const d=Object.getOwnPropertyDescriptor(globalThis,'__zk1306CanvasObserver');if(!d||!Object.hasOwn(d,'value'))throw new Error('Missing private observer');const run=Object.getOwnPropertyDescriptor(d.value,'run');if(!run||!Object.hasOwn(run,'value')||typeof run.value!=='function')throw new Error('Private observer run unavailable');return run.value();}
export function prepareFixture(fixture){
 const acquisition="const c=document.querySelector('canvas'),g=c.getContext('2d');",lastDraw="g.fillRect(0,0,4,4);";
 if(fixture.split(acquisition).length!==2||fixture.split(lastDraw).length!==2)throw new Error('Donor anchors');
 const before='/*ZK1306_INSTALL_BEGIN*/const __zk1306Inline=('+installCanvasStateObserver.toString()+')(c,g);/*ZK1306_INSTALL_END*/',after="/*ZK1306_S0_BEGIN*/__zk1306Inline.snapshot('S0_INLINE_POSTDRAW');/*ZK1306_S0_END*/";
 return {html:fixture.replace(acquisition,acquisition+before).replace(lastDraw,lastDraw+after),insertions:[before,after]};
}
export const failureKind=value=>value===null?'null':typeof value;
export function firstFailure(state,error){if(!state.failed){state.failed=true;state.primary=error;state.firstKind=failureKind(error);}}
export function createEventLedger(){
 const state={valid:true,overflow:false,malformed:false,closed:false,pageerrorState:'NONE',consoleState:'NONE',pageerrors:[],console:[]};
 const data=(object,key)=>{for(let i=0;object&&i<8;i++,object=Object.getPrototypeOf(object)){const d=Object.getOwnPropertyDescriptor(object,key);if(d){if(!Object.hasOwn(d,'value'))throw 0;return d.value;}}throw 0;};
 const add=(name,row)=>{if(state[name].length>=16||Buffer.byteLength(JSON.stringify(row))>512||Buffer.byteLength(JSON.stringify({pageerrors:name==='pageerrors'?[...state.pageerrors,row]:state.pageerrors,console:name==='console'?[...state.console,row]:state.console}))>8192){state.valid=false;state.overflow=true;return;}state[name].push(row);};
 const receive=(name,event)=>{if(state.closed)return;const key=name==='pageerrors'?'pageerrorState':'consoleState';state[key]='OBSERVED';try{let row;if(name==='pageerrors'){const n=data(event,'name'),message=data(event,'message');if(typeof n!=='string'||typeof message!=='string'||Buffer.byteLength(n)>64)throw 0;row={name:n,message};}else{const type=data(event,'type'),text=data(event,'text');if(typeof type!=='function'||typeof text!=='function')throw 0;const t=type.call(event),m=text.call(event);if(typeof t!=='string'||typeof m!=='string'||Buffer.byteLength(t)>64)throw 0;row={type:t,text:m};}add(name,row);}catch{state.valid=false;state.malformed=true;state[key]='MALFORMED';}};
 return {pageerror:event=>receive('pageerrors',event),console:event=>receive('console',event),freeze:()=>{state.closed=true;return {...state,pageerrors:state.pageerrors.map(x=>({...x})),console:state.console.map(x=>({...x}))};}};
}
export function sanitizeTrace(value){
 let nodes=0;
 const copy=(object,depth=0)=>{if(++nodes>2048||depth>8)throw 0;if(object===null||typeof object==='boolean')return object;if(typeof object==='number'){if(!Number.isFinite(object)||Math.abs(object)>1e12)throw 0;return object;}if(typeof object==='string'){if(Buffer.byteLength(object)>512)throw 0;return object;}if(!object||typeof object!=='object')throw 0;const keys=Reflect.ownKeys(object);if(keys.length>64)throw 0;const data=key=>{const d=Object.getOwnPropertyDescriptor(object,key);if(!d||!Object.hasOwn(d,'value'))throw 0;return d.value;};if(Array.isArray(object)){const length=data('length');if(length>64||keys.length!==length+1)throw 0;const out=[];for(let i=0;i<length;i++)out.push(copy(data(String(i)),depth+1));return out;}const out=Object.create(null);for(const key of keys){if(typeof key!=='string')throw 0;out[key]=copy(data(key),depth+1);}return out;};
 try{const trace=copy(value),labels=['S0_INLINE_POSTDRAW','S1_POSTLOAD','S2_FIRST_RAF','S3_SECOND_RAF'];if(trace.schemaVersion!==1||typeof trace.valid!=='boolean'||typeof trace.complete!=='boolean'||!Number.isInteger(trace.frameCallbacks)||trace.frameCallbacks<0||trace.frameCallbacks>2||trace.stages.length>4||trace.getImageDataCalls>4||trace.contextEvents.length>16||trace.dimensions.length>16||trace.compositor!=='UNKNOWN'||trace.frozen!==true)throw 0;if(trace.complete&&(trace.stages.length!==4||trace.getImageDataCalls!==4||trace.frameCallbacks!==2||trace.stages.some(row=>row.imageRead!==true||row.pixelMismatchCount===null||row.channelMismatchCount===null)))throw 0;for(let i=0;i<trace.stages.length;i++){const row=trace.stages[i];if(row.ordinal!==i+1||row.stage!==labels[i]||row.samples.length!==6)throw 0;for(let j=0;j<6;j++){const xy=[[0,0],[3,3],[4,0],[15,15],[16,0],[31,15]][j],sample=row.samples[j];if(sample.length!==6||sample[0]!==xy[0]||sample[1]!==xy[1])throw 0;for(const n of sample.slice(2))if(n!==null&&(!Number.isInteger(n)||n<0||n>255))throw 0;}if(row.pixelMismatchCount!==null&&(!Number.isInteger(row.pixelMismatchCount)||row.pixelMismatchCount<0||row.pixelMismatchCount>512))throw 0;if(row.channelMismatchCount!==null&&(!Number.isInteger(row.channelMismatchCount)||row.channelMismatchCount<0||row.channelMismatchCount>2048))throw 0;}return {valid:true,trace};}catch{return {valid:false,trace:{valid:false,malformed:true,reason:'MALFORMED_TRACE',stages:[],contextEvents:[],dimensions:[]}};}
}
export async function runController(page,fixture){
 const ledger=createEventLedger(),listeners=[],failure={failed:false,primary:undefined};let observation;
 try{for(const [name,fn]of [['pageerror',ledger.pageerror],['console',ledger.console]]){page.on(name,fn);listeners.push([name,fn]);}await page.setContent(fixture,{waitUntil:'load',timeout:10000});observation=await page.evaluate(consumeCanvasObserver);const early=sanitizeTrace(observation);if(early.valid&&early.trace.firstFailurePresent&&!failure.failed){failure.failed=true;failure.primary=undefined;failure.firstKind=early.trace.firstFailureKind;failure.primaryTransported=false;}}catch(error){firstFailure(failure,error);}finally{for(const [name,fn]of listeners)try{page.off(name,fn);}catch(error){firstFailure(failure,error);}}
 const events=ledger.freeze(),sanitized=sanitizeTrace(observation);if(!events.valid||!sanitized.valid)firstFailure(failure,new Error('Invalid observation'));const trace=sanitized.trace;
 if(trace.complete!==true)firstFailure(failure,new Error('Incomplete four-stage trace'));
 if(Buffer.byteLength(JSON.stringify({pageerrors:events.pageerrors,console:events.console,contextEvents:trace.contextEvents,dimensions:trace.dimensions}))>8192){events.overflow=true;events.valid=false;firstFailure(failure,new Error('Combined events overflow'));}
 return {failure,events,trace};
}
export function publishBoundedReport(io,path,result,failure){
 let record=result,text=JSON.stringify(record,null,2)+'\n';if(Buffer.byteLength(text)>16384){firstFailure(failure,new Error('Report cap'));record={unit:result.unit,outcome:'REPORT_OVERFLOW_FAIL',reportOverflow:true,firstFailurePresent:true,firstFailureKind:(failure.firstKind??failureKind(failure.primary)),helperInvocations:0,CDPSessions:0,screenshots:0,releaseCleared:false};text=JSON.stringify(record)+'\n';}
 try{io.writeFileSync(path,text,{flag:'wx'});}catch(error){firstFailure(failure,error);return {written:false,record:{...record,outcome:'REPORT_IO_FAIL',firstFailurePresent:true,firstFailureKind:failure.firstKind??failureKind(failure.primary)}};}return {written:true,record};
}
export function assertSourceFence(source){if(/captureVisibleCanvas|newCDPSession|\.send\s*\(|captureScreenshot|\.screenshot\s*\(|import\s*\([^)]*helperPath|evaluateHandle|jsonValue|\.args\s*\(/.test(source))throw new Error('Forbidden capture route');return true;}
